### ISSUE TITLE
Layered Nav Widget is not functioning

### ISSUE THREAD

**Issue by PDSXerox** [woothemes/woocommerce#11123]
## EXPLANATION OF THE ISSUE

I have the site set up to filter product attributes based on a dropdown search using five Layer Nav widgets. Each of these is set up as an AND query, and I check all the products, they have the appropriate tags. When I select one option, almost all other options in the resulting generated page disappear. 

## STEPS TO REPRODUCE THE ISSUE

go to: www.pds-co.com and select the link, "Printers" from the main nav bar. A product finder will appear in the right sidebar. Select an option, for reproduction, choose, "ConnectKey Enabled". The other 4 product finder option vanish from the generated results, even though there are floor / desktop, color or B&W and other options within that group of products that are now unfindable using that tool.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by PDSXerox** [comment]
Forgot the system status report:

`
### WordPress Environment ###

Home URL: http://www.pds-co.com
Site URL: http://www.pds-co.com
WC Version: 2.6.0
Log Directory Writable: ✔
WP Version: 4.5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.5.9-1ubuntu4.17 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 0
PHP Max Input Vars: 5000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.29
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.0
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (30) ###

Gravity Forms: by rocketgenius – 1.9.19
LayerSlider WP: by Kreatura Media – 5.6.6
Admin Color Schemes: by WordPress Core Team – 2.2
Akismet: by Automattic – 3.1.11
iThemes Security: by iThemes – 5.5.0
Click To Tweet: by Todaymade – 1.3
Duplicate Post: by Enrico Battocchi – 2.6
Facebook Conversion Pixel: by Kellen Mace – 1.3.4
Fusion Core: by ThemeFusion – 2.0.3
Gravity Forms Logging Add-On: by rocketgenius – 1.0.2
Jetpack by WordPress.com: by Automattic – 4.0.3
MailPoet Gravity Forms Add-on: by Sebs Studio – 2.0.4
Pretty Link Lite: by Caseproof – 1.6.9
Redirection: by John Godley – 2.4.4
Slider Revolution: by ThemePunch – 5.2.5
Search By SKU - for Woocommerce: by Matthew Lawson – 0.6.1
Search Exclude: by Roman Pronskiy – 1.2.2
SendGrid: by SendGrid – 1.8.1
WooCommerce Catalog Visibility Options: by Lucas Stark – 2.8.1
WooCommerce Custom Product Tabs Lite: by SkyVerge – 1.5.0
WooCommerce Authorize.net AIM Gateway: by WooThemes / SkyVerge – 3.7.0
WooCommerce Product CSV Import Suite: by WooThemes – 1.10.10
Woocommerce Super Simple Tax Exemption: by Bobbie Wilson – 1.3
WooCommerce Video Product Tab: by Sebs Studio – 2.3.1
WooCommerce: by WooThemes – 2.6.0
WooThemes Helper: by WooThemes – 1.6.2
Yoast SEO: by Team Yoast – 3.3.0
WP SEO HTML Sitemap: by Magna Technology
LLC – 0.9.6

WP Smush: by WPMU DEV – 2.3.1
MailPoet Newsletters: by MailPoet – 2.7.2

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #603 - /shop/
Cart: #4128 - /cart/
Checkout: #4129 - /checkout/
My Account: #4131 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Avada Child
Version: – 0 is available
Author URL: 
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 4.0.3
Parent Theme Author URL: http://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
Avada/woocommerce/single-product/product-image.php
Avada/woocommerce/single-product/product-thumbnails.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php


### Authorize.net AIM ###

Environment: Production
`

**Comment by mikejolley** [comment]
That is **not** woocommerce core. What powers those dynamic widgets? If it's not been WooCommerce 2.6 tested it likely is not compatible with the updated logic in 2.6.

**Comment by PDSXerox** [comment]
From: https://docs.woothemes.com/document/woocommerce-widgets/ (AKA: WooCommerce)

Included Widgets ↑ Back to Top
WooCommerce Average Rating Filter – Allow the user to refine products based on customer ratings.
WooCommerce Cart – Displays the shopping cart contents and links to the cart / checkout
**WooCommerce Layered Nav** – Allows the user to refine products based on attributes
WooCommerce Layered Nav Filters – Shows active layered nav filters so users can see and deactivate them.
WooCommerce Price Filter – Allow the user to refine products based on price on product category pages
WooCommerce Product Categories – Display product categories in list format
WooCommerce Products – This includes view for All Products, Featured Products, and On-Sale Products.
WooCommerce Product Search – Search products only
WooCommerce Product Tags  – Display product tags in tag cloud format
WooCommerce Recently Viewed – Display a list of products the customer has recently viewed
WooCommerce Recent Reviews – List recent customer reviewed products with ratings
WooCommerce Top Rated Products – Display a list of top rated products

**Comment by mikejolley** [comment]
I know its a layered nav widget, but you have them appearing in sequence. This is not standard. What powers that..

**Comment by PDSXerox** [comment]
OIC what you're saying ... Jetpack.

**Comment by mikejolley** [comment]
I only see desktop devices as a feature right now. 

Go to System Status > Tools and trigger a term recount.

**Comment by PDSXerox** [comment]
Done. I'm seeing that too even after. Thanks for the assistance btws!

**Comment by mikejolley** [comment]
Other than desktop, what else should be there?

**Comment by mikejolley** [comment]
I see 14 products, all desktop.

**Comment by PDSXerox** [comment]
Floor placement, like the big beasty machines most offices have

**Comment by mikejolley** [comment]
Your homepage link is going to http://www.pds-co.com/category/office-document-systems/office-printers/ - none of these seem to be floor placement?

**Comment by mikejolley** [comment]
Can you turn off the jetpack functionality for now so we can just see all the widgets working at once? Might make things clearer!

**Comment by PDSXerox** [comment]
Done!

**Comment by mikejolley** [comment]
Is there caching active here? Not seeing options still.

**Comment by PDSXerox** [comment]
I cleared the cache after disabling the plugin, this is on a separate sidebar from the WP blog default sidebar. I'm seeing all widgets on any given product page. If it's based on the tags, would all the widgets appear if they are not relevant? Thank you again.

**Comment by mikejolley** [comment]
This is all I see http://glui.me/?i=u0p15hgvf1zp551/2016-06-14_at_23.04.png/

**Comment by PDSXerox** [comment]
I cleared the cache again from the host (WP Engine) and Content Delivery caching is off. I'm seeing the same thing you are. I'm starting to think it's a theme issue (Avada). I might roll the site back and wait to see if there's a theme update in a bit.

**Comment by mikejolley** [comment]
I do see options disappear after selections, e.g. going to http://www.pds-co.com/category/office-document-systems/?filtering=1&filter_connect-key-enabled=connectkey-enabled-yes&filter_find-pages-per-minute=find-pages-per-minute-30-less

How does it look with list based nav instead of dropdown?

**Comment by PDSXerox** [comment]
Hmm... when I made the first five "lists", a few more widgets showed up.

**Comment by mikejolley** [comment]
Ok, final thing. Can you open all widget settings and screenshot so I can see relations? I'm still not sure if there is a bug here since you're using 'and' logic.

**Comment by PDSXerox** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/19938128/16062013/d74e2520-324d-11e6-8abb-b76187a298dc.jpg)

**Comment by mikejolley** [comment]
@PDSXerox just made 2 commits. Can you apply those and see what changes it makes on your site. Don't forget to flush all cache.

**Comment by mikejolley** [comment]
The above fixes counts on category and tag archives. Previously it would count ignoring what category you are inside.

**Comment by PDSXerox** [comment]
There is no way top get counts in that widget from product categories. I changed the and operator to or and the problem remains.

**Comment by mikejolley** [comment]
To clarify, the counts in the layered nav did not consider the currently viewed category. That has been fixed.

**Comment by PDSXerox** [comment]
OK, Fixed in a new update then?

**Comment by mikejolley** [comment]
It will be, but if you can apply the above 2 commits to your install in advance that would help.

**Comment by PDSXerox** [comment]
Hi M,

Changed all the, 'ANDs' to, 'ORs' and made the change to the file. Purged all caches and it looks like that issue is still around.

**Comment by mikejolley** [comment]
Email me ftp and I'll take a look at the setup, but I do require you to disable all caches whilst it's worked on.

mike.jolley@automattic.com
