### ISSUE TITLE
Bug with quantity input on 7.4

### ISSUE THREAD

**Issue by daveloodts** [woothemes/woocommerce#36920]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Since 7.4: when Managing Stock on variation level; the quantity inout field ignores the stock number; and the buyer is able to continue clicking up the numbers/

All credits goes to Emmanouil who brought on the bug on wordpress.org forum:
https://wordpress.org/support/topic/bug-with-quaninty-input-on-7-4/

### Expected behavior

The quantity incrementor should stop on the max. stick number, as in 7.3

### Actual behavior

The quantity incrementor does not stop, people ca, assume to can order more then there is in stock. Result: a disappointment after clicking the buy button.

### Steps to reproduce

To reproduce the issue do the following:

- Create a new variable product
- Add two random variants with manage stock enabled and put a stock of your liking
- Go to the product page now, select any variant an try to increase the quantity
- You will see that the counter adds up with no limit. The only way to fix this is to downgrade to 7.3.

### WordPress Environment

it concerns all woocommerce sites running on 7.4; and handling "manage stocks" for variable products.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by tammullen** [comment]
Hi @daveloodts ! Thanks for reporting. This is a known issue and is being worked on, the fix will be likely be available in the next release.

https://github.com/woocommerce/woocommerce/issues/36855

**Comment by daveloodts** [comment]
Hi @tammullen; yes, sorry i noticed your reaction in the forum. Thanks! I also reacted on the forum, but my responses are sadly delayed on the forum _(i'm under modwatch for quit some time, hard to get rid of it, can take years)._ So, there's an upcoming note in the forum, nevermind that.

**Comment by xue28** [comment]
5987518-zen

**Comment by jonathansadowski** [comment]
Thanks for the report! As this was fixed via #36871, I'm going to close this issue. This is due to be included with the 7.5 release.

**Comment by LeafMaps** [comment]
New to GitHub, apologies if I'm not posting correctly. Is there an ETA on the release of 7.5?

**Comment by jonathansadowski** [comment]
> New to GitHub, apologies if I'm not posting correctly. Is there an ETA on the release of 7.5?

7.5 is planned for release on March 14.

**Comment by calyweb** [comment]
7.5 is released, but the problem is not solved at all ...
![Capture d’écran 2023-03-14 à 17 14 55](https://user-images.githubusercontent.com/63538887/225069117-f12da810-2f2e-4942-ac47-9946465ca47d.png)

**Comment by Edwynn** [comment]
I updated Woocommerce to version 7.5 and it doesn't solve the problem. 
I am installing storefront and only Woocommerce in test environment.

**Comment by ben72** [comment]
Same issue for me in 7.5! @jonathansadowski was the fix really released in 7.5?

**Comment by tammullen** [comment]
See https://github.com/woocommerce/woocommerce/issues/37129#issuecomment-1471640229
The fix will be included in an upcoming fix release

**Comment by jonathansadowski** [comment]
Sorry that this wasn't included in 7.5.0. We've just released a 7.5.1 fix release which should address this issue.

**Comment by ben72** [comment]
@jonathansadowski Perfect, it's working now! Thanks to everybody who contributed to the fix!
