### ISSUE TITLE
Attributes Missing After Update the Product

### ISSUE THREAD

**Issue by skytseng1978** [woothemes/woocommerce#37750]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After I upgraded the Woocommerce to version 7.6.0, after updating the product page, sometimes attributes were missing, could you help me to check this problem, thank you.

### Expected behavior

The product have 7 attributes, after update still have 7 attributes.

### Actual behavior

Attribute 7 becomes 6 after updating the product page.

### Steps to reproduce

https://www.dropbox.com/s/wdczf89m980teh0/Attributes%20Missing%20after%20Update%20the%20Product.mp4?dl=0

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.businessexpertpress.com
Site address (URL): https://www.businessexpertpress.com
WC Version: 7.6.0
REST API Version: ✔ 7.6.0
WC Blocks Version: ✔ 9.8.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_fcgid/2.3.9 PHP/7.4.33
PHP Version: 7.4.33
PHP Post Max Size: 384 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.44

SUHOSIN Installed: –
MySQL Version: 5.6.47
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.6.0
WC Database Prefix: wp_
Total Database Size: 235.51MB
Database Data Size: 179.42MB
Database Index Size: 56.09MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.42MB + Index: 0.53MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.33MB + Index: 0.30MB + Engine InnoDB
wp_aryo_activity_log: Data: 1.02MB + Index: 0.00MB + Engine InnoDB
wp_aws_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aws_index: Data: 32.14MB + Index: 26.13MB + Engine InnoDB
wp_cky_banners: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_cky_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cky_cookie_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_db7_forms: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 5.25MB + Index: 1.25MB + Engine InnoDB
wp_postmeta: Data: 81.53MB + Index: 21.77MB + Engine InnoDB
wp_posts: Data: 31.52MB + Index: 3.53MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_revslider_css_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_revslider_sliders_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.30MB + Index: 0.23MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.27MB + Index: 0.22MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.14MB + Index: 0.28MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 2.28MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 14.55MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 1.02MB + Index: 0.22MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 6.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 2776
custom_css: 1
customize_changeset: 9
dflip: 1179
is_search_form: 1
nav_menu_item: 49
page: 1186
post: 14
product: 1156
revision: 5588
shortcoder: 29
wpcf7_contact_form: 2
wpcode: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

3D FlipBook : Dflip Lite: by DearHive – 1.7.35
Ultimate Addons for WPBakery Page Builder: by Brainstorm Force – 3.19.13
Ivory Search: by Ivory Search – 5.5.1
Advanced Woo Search: by ILLID – 2.76
Activity Log: by Activity Log Team – 2.8.5
Classic Widgets: by WordPress Contributors – 0.3
Cloudflare: by Cloudflare
Inc. – 4.11.0

Contact Form 7: by Takayuki Miyoshi – 5.7.5.1
Contact Form CFDB7: by Arshid – 1.2.6.5
CookieYes | GDPR Cookie Consent: by CookieYes – 3.0.8
The7 Elements: by Dream-Theme – 2.7.4
Duplicate Page: by mndpsingh287 – 4.5.1
Site Kit by Google: by Google – 1.98.0
WPCode Lite: by WPCode – 2.0.9
WPBakery Page Builder: by Michael M - WPBakery.com – 6.10.0
Lockdown WP Admin: by Sean Fisher – 2.3.2
Slider Revolution: by ThemePunch – 6.6.10
Shortcoder: by Aakash Chakravarthy – 6.2
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.23.3

Booster for WooCommerce: by Pluggabl LLC – 6.0.5
WooCommerce: by Automattic – 7.6.0
Wordfence Security: by Wordfence – 7.9.2
WP File Manager: by mndpsingh287 – 7.1.8
WP Mail SMTP: by WPForms – 3.7.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #7 - /all-titles/
Cart: ❌ Page visibility should be public
Checkout: ❌ Page visibility should be public
My account: ❌ Page visibility should be public
Terms and conditions: #767 - /terms-and-conditions/

### Theme ###

Name: The7
Version: 11.6.4
Author URL: https://dream-theme.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: dt-the7/woocommerce/cart/cart.php version 7.0.1 is out of date. The core version is 7.4.0
dt-the7/woocommerce/cart/cross-sells.php
dt-the7/woocommerce/cart/mini-cart.php
dt-the7/woocommerce/checkout/form-billing.php
dt-the7/woocommerce/checkout/form-checkout.php
dt-the7/woocommerce/checkout/form-coupon.php
dt-the7/woocommerce/checkout/form-login.php
dt-the7/woocommerce/checkout/form-shipping.php
dt-the7/woocommerce/checkout/review-order.php
dt-the7/woocommerce/checkout/thankyou.php
dt-the7/woocommerce/content-product.php
dt-the7/woocommerce/content-widget-product.php
dt-the7/woocommerce/content-widget-reviews.php
dt-the7/woocommerce/global/breadcrumb.php
dt-the7/woocommerce/global/form-login.php
dt-the7/woocommerce/global/quantity-input.php version 7.2.0 is out of date. The core version is 7.4.0
dt-the7/woocommerce/loop/loop-end.php
dt-the7/woocommerce/loop/loop-start.php
dt-the7/woocommerce/loop/pagination.php
dt-the7/woocommerce/myaccount/form-login.php
dt-the7/woocommerce/notices/error.php
dt-the7/woocommerce/notices/notice.php
dt-the7/woocommerce/notices/success.php
dt-the7/woocommerce/order/order-details-customer.php
dt-the7/woocommerce/order/order-details.php
dt-the7/woocommerce/single-product/meta.php
dt-the7/woocommerce/single-product/price.php
dt-the7/woocommerce/single-product/related.php
dt-the7/woocommerce/single-product/up-sells.php
dt-the7/woocommerce/content-product_cat.php

Outdated Templates: ❌
					
					
						Learn how to update

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: block-editor-feature-enabled
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-04-18 02:55:02 -04:00
Options: ✔
Notes: 92
Onboarding: completed

### Action Scheduler ###

Complete: 1,394
Oldest: 2023-03-17 04:58:49 -0400
Newest: 2023-04-16 22:40:51 -0400

Failed: 5
Oldest: 2023-02-24 08:01:44 -0500
Newest: 2023-04-13 22:31:00 -0400

Pending: 2
Oldest: 2023-04-17 06:08:05 -0400
Newest: 2023-04-17 13:19:22 -0400

### Status report information ###

Generated at: 2023-04-16 23:06:23 -04:00
`

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by syntaxerror** [comment]
Have noticed the same issue, suspecting it's related to the changes in https://github.com/woocommerce/woocommerce/pull/36944

Another thing is that it was possible to add new attributes in 7.5.1 and just hit the 'Update' button, and they would save, while we have to click the 'Save attributes' button in 7.6.0 first, else they get lost.

Also noted the status of the 'Save attributes' button changed, in 7.5.1 it was always clickable for those products, while it's disabled in 7.6.0

7.5.1:
![751](https://user-images.githubusercontent.com/858132/232410948-1ca5e00a-f550-4f90-a838-fe65f630f86a.png)

7.6.0:
![760](https://user-images.githubusercontent.com/858132/232410983-ae350ee0-7435-4797-a12d-3eeea5d57a52.png)

_Edit! Noticed the change for 'Save Attributes' button is related to https://github.com/woocommerce/woocommerce/pull/37046 - which one of the changes causing the bug is still unclear though._

**Comment by ronnyadsetts** [comment]
Just to add to this, we're seeing the issue too. We're seeing a global attributes being removed following products being edited.

It's pretty inconvenient as we have hundreds of products with tens of products edited every day. It essentially triples the amount of time for each edit.

**Comment by Euroracers** [comment]
> Just to add to this, we're seeing the issue too. We're seeing a global attributes being removed following products being edited.
> 
> It's pretty inconvenient as we have hundreds of products with tens of products edited every day. It essentially triples the amount of time for each edit.

You can better put your feedback here: https://github.com/woocommerce/woocommerce/issues/37761
It is reported as a bug, hopefully it will be fixed soon.

We have 100+ woocommerce websites we manage and 100.000+ affiliate products so we don't touch them untill there is a solution.

**Comment by xue28** [comment]
6220538-zen

**Comment by andy-jam** [comment]
We have the same issue.

I’ve been looking at the wp_postmeta table.

For a selected product:

SELECT * FROM wp_postmeta WHERE post_id = 507902 AND meta_key = “_product_attributes”

gives:

a:1:{s:9:”sub-group”;a:6:{s:4:”name”;s:9:”Sub-Group”;s:5:”value”;s:4:”HD15″;s:11:”is_taxonomy”;i:0;s:8:”position”;i:0;s:10:”is_visible”;i:0;s:12:”is_variation”;i:0;}}

Updating the product without any editing and the query gives Empty Set.

Recreating the the Sub-Group attribute manually gives:

a:1:{s:12:”pa_sub-group”;a:6:{s:4:”name”;s:12:”pa_sub-group”;s:5:”value”;s:0:””;s:8:”position”;i:0;s:10:”is_visible”;i:0;s:12:”is_variation”;i:1;s:11:”is_taxonomy”;i:1;}}

All of these products are imported using WooCommerce Product CSV Import Suite it’s been working fine for at least 18 months.

That “pa_” is certainly new.

I suspect that any product with attributes created before 7.6 will lose their attributes if the product is updated even without any changes. Just hit update.

Our site has 460,000+ products. All with attributes.

**Comment by xue28** [comment]
6215984-zen

For this particular thread, this is the scenario:

- Duplicate an old product with attributes that was created prior to the 7.6.0 update
- Publish the product 
- Notice that the attributes of this duplicated product were deleted after publish

**Comment by syntaxerror** [comment]
@xue28 you don't need to duplicate an old product, it happens even if you update the old product itself - just need to push the publish button. That's what this report is about, and that's what "everyone" is struggling with around the world those days, waiting for someone to fix the issues caused by some badly tested fancy and unneeded changes ...

**Comment by xue28** [comment]
@syntaxerror Hi! What I'm trying to say in my comment, is that for that specific scenario, that is what's happening and I was able to replicate it on my test site. 

Because, if you duplicate a newly created product, the attributes for the duplicated product are not being deleted. This only happens for old products that were created prior to the 7.6.0 update.

**Comment by syntaxerror** [comment]
OK, but as you wrote "For this particular thread, this is the scenario:" it seemed like it was for this hole thread, which is not. It applies to all old product with non cart attributes.

**Comment by xue28** [comment]
Sorry for the confusion, I am referring to our internal ticketing system for ticket #6215984 here.

**Comment by Tonuz** [comment]
Same error here :(

**Comment by jhhuisman** [comment]
Same issue.
After adding the same attributes again to the product the issue is resolved and saving works fine (it keeps the attributes).
I looked into the HTML difference between an 'old product' version with attributes that get lost after saving and the version after adding back the attributes. There is one difference. Perhaps this might help the authors.

Failing version:
```<label><input type="checkbox" class="checkbox" name="attribute_variation[0]" value="1"> Used for variations</label>```

Restored version:
```<label><input type="checkbox" class="checkbox" checked="checked" name="attribute_variation[0]" value="1"> Used for variations</label>```

Hope it get's fixed soon. For now I will downgrade WooCommerce until this is resolved.

**Comment by bluantinoo** [comment]
It looks like this annoying bug is fixed in newer versions https://github.com/woocommerce/woocommerce/issues/37761

**Comment by rrennick** [comment]
@bluantinoo Thanks for the follow up.

**Comment by XanderCam** [comment]
I still have this problem on december 2023

**Comment by TomasHurtz** [comment]
I also still have this issue in Feb 2024 - the strange thing is, on my staging site it does not happen, but on my production site it happens when I try to update the post / page.  The woo attributes get lost, but if I update the woo product attributes in the woo section of the product post, they save ok.  

It only gives problem when I update the main post using top right blue button.....
