### ISSUE TITLE
[Enhancement]: Remove “Congratulations on the sale. Process your orders on the go. Get the app.” from the new orders emails

### ISSUE THREAD

**Issue by fvdbgit** [woothemes/woocommerce#38389]
### Describe the solution you'd like

Please remove the “Congratulations on the sale. Process your orders on the go. Get the app.” sentences from the new orders emails.
It is useless and it is annoying for people using those emails as a confirmation email for customers or for people printing those emails to put them into the box with the products to ship to customers.

### Describe alternatives you've considered

An alternative would be to add an option into the WooCommerce settings to remove this sentence for people who do not want it.

**Comment by jorgeatorres** [comment]
Hi @fvdbgit!

Part of the message you were seeing comes from the "Additional Content" setting in the e-mail (WooCommerce > Settings > Emails > New order). Even if you removed this text, it'll still use a default. This was clearly a bug and we have fixed it in #47809, which should go out soon with 9.1.0.

As for the app link, this can easily be removed with a PHP snippet like the following, which could be enabled via a plugin like [Code Snippets](https://wordpress.org/plugins/code-snippets/).

```php
<?php
add_action(
	'woocommerce_email',
	function ( $wc_emails ) {
		remove_filter( 'woocommerce_email_footer', array( $wc_emails->emails['WC_Email_New_Order'], 'mobile_messaging' ), 9 );
	}
);
```

Keep in mind that the new order e-mail is only sent to admins/shop managers, and isn't meant to be read by buyers. If you want to further customize this e-mail for other uses, you can override the template inside your theme, which can be done by copying the file `woocommerce/templates/emails/admin-new-order.php` to `<your theme directory>/woocommerce/emails/admin-new-order.php`.
Provided permissions are correct, you can do this easily (and even edit the template!) directly from WooCommerce > Settings > Emails > New order.

Please let us know if the above helps or if I've missed something.

**Comment by Nodetar** [comment]
@jorgeatorres Please describe exactly which code you have to insert into the template and WHERE exactly it has to go if you don't want to use an additional plugin to remove the email app text. It is still not entirely clear.

**Comment by jorgeatorres** [comment]
Hey @Nodetar!

The snippet I shared above _needs_ to go into your theme's `functions.php` or used through plugins such as Code Snippets, as indicated.

If you want to do this as a template override, one option would be to copy `woocommerce/templates/emails/email-mobile-messaging.php` to `<current theme's directory>/emails/email-mobile-messaging.php` and making the changes to change the text. An empty file would do if you want to remove it completely.

**Comment by jorgeatorres** [comment]
After some discussion, we're closing this issue for now. The app prompt only appears under specific circumstances (and only in e-mails to admins, not buyers). There are also various ways to remove the text or completely override the e-mail template to prevent it from appearing.

We'll be more than happy to revisit the decision if there's something we've missed or this is creating other problems.
