### ISSUE TITLE
Filter Block Buttons appearing differently in the editor vs the front end 

### ISSUE THREAD

**Issue by vivialice** [woothemes/woocommerce#42591]
The button styles for the theme aren't translating over to the front end for some reason. In this example from the pre-set styles in the TT2 theme, buttons are shown with a border radius in the editor but aren't showing in the front end. 

<img width="655" alt="Screenshot 2022-09-09 at 14 07 04" src="https://user-images.githubusercontent.com/9888201/189692476-28d1e7dd-c951-4e13-b298-8e413cd32dff.png">

<img width="1140" alt="Screenshot 2022-09-09 at 13 51 09" src="https://user-images.githubusercontent.com/9888201/189692507-90955d4c-2f84-4617-b763-4575f9f5cda0.png">

**Comment by danielwrobert** [comment]
X-linking woocommerce/woocommerce-blocks#7203 for an additional example to reference.

**Comment by danielwrobert** [comment]
Hi, @vivialice! 👋 

I'm not able to replicate this. I'm seeing a border radius on the buttons for both the editor and front-end:

**Editor:**
<img width="796" alt="CleanShot 2022-09-23 at 10 26 26@2x" src="https://user-images.githubusercontent.com/481776/191984881-be23110e-01cb-4223-965a-2968194498ba.png">

**Front-end:**
<img width="925" alt="CleanShot 2022-09-23 at 10 26 48@2x" src="https://user-images.githubusercontent.com/481776/191984932-f447ca36-3b40-46b7-96cb-462db61fd11e.png">

Note: I also tested with other Global Style configurations in the TT2 theme.

In case I'm missing something, can you provide some more details on the steps to reproduce?

**Comment by gigitux** [comment]
Same, I'm not able to replicate this issue. Also, on my setup with TT2 the buttons  don't have the border-radius:

![image](https://user-images.githubusercontent.com/4463174/192293729-d691c6e4-8768-4806-84c1-f3ed3f80a501.png)

**Comment by vivialice** [comment]
hmm I am not sure what is going on. I did a review over Zoom with @danielwrobert and all my site settings are the same. I get the same result when I change to any style.

**Comment by gigitux** [comment]
Could you try to remove-add the blocks again? Also, are you sure that you don't have any global styles enabled?
Can you share your version of WordPress and your version of Gutenberg? 

Thanks! 🙇

**Comment by vivialice** [comment]
@gigitux I'll give that a go and report back! 

> Also, are you sure that you don't have any global styles enabled?
 
Yup 

>  Can you share your version of WordPress and your version of Gutenberg?

WP v6.0.2 and GB v14.1.1

**Comment by gigitux** [comment]
I just tried again with your setup, and I'm not able to replicate it :'(

**Comment by vivialice** [comment]
I just tried it again too and I am still getting the same result! So strange. 🤔

**Comment by vivialice** [comment]
Are you testing on a page or a template?

**Comment by gigitux** [comment]
> Are you testing on a page or a template?

I'm testing it on a template. Could you try on a new website?

**Comment by vivialice** [comment]
Okay I tried on a different site and it's looking a lot better! The sizes still look slightly different to me though, are you seeing the same? 

Editor:

<img width="542" alt="Screenshot 2022-09-28 at 15 45 17" src="https://user-images.githubusercontent.com/9888201/192810213-c35db0d6-e35b-472c-92a0-539f45f44f22.png">

Front end:

<img width="649" alt="Screenshot 2022-09-28 at 15 45 22" src="https://user-images.githubusercontent.com/9888201/192810271-31e6dc44-c7d9-4194-9de3-da04d14a9b82.png">

**Comment by imanish003** [comment]
I can see on my local setup that `Apply` button size is different for `Filter by Attribute` block.
In other words, All other filter blocks have different `Apply` button size than `Filter by Attribute` block. 

@vivialice I quickly created a small PR that should fix this issue. Can you please a look at following draft PR?
https://github.com/woocommerce/woocommerce-blocks/pull/7578

| Before | After |
| ------ | ----- |
|    ![Screenshot 2022-11-04 at 4 59 27 PM](https://user-images.githubusercontent.com/16707866/199962392-c562d4a4-f291-48aa-8b34-5f255760f015.png)    |    ![Screenshot 2022-11-04 at 4 58 59 PM](https://user-images.githubusercontent.com/16707866/199962427-c11e978d-fec6-4deb-a38d-72a3fbbc7482.png)   |
| ![image](https://user-images.githubusercontent.com/16707866/199962603-1044b4ca-2f52-4ba5-8d98-af86caf145f0.png) | ![image](https://user-images.githubusercontent.com/16707866/199962733-e78105ca-c541-4b5a-91b2-38c6804d2c3a.png) |

**Comment by imanish003** [comment]
@vivialice Just a gentle reminder. Looks like you missed my previous comment 🙂

**Comment by vivialice** [comment]
@imanish003 Aplogies! Sometimes I miss Github pings. 

I still see a different button in the editor vs the front-end. However, they are all the same size. 

Editor:
<img width="591" alt="Screenshot 2022-11-16 at 17 52 16" src="https://user-images.githubusercontent.com/9888201/202256068-055ac66c-6079-4b00-94e9-7fc00d16684c.png">

Front-End:
<img width="712" alt="Screenshot 2022-11-16 at 17 52 28" src="https://user-images.githubusercontent.com/9888201/202256107-bd4c584c-dc52-4578-a902-9f34f4c34ad5.png">

**Comment by imanish003** [comment]
@vivialice Thanks for taking a look 🙏 

> I still see a different button in the editor vs the front-end. However, they are all the same size.

May I know If you tried it on `fix/7119-apply-button-styling` branch? As mentioned in my last comment, I did fix it in PR woocommerce/woocommerce-blocks#7578. Therefore you will need to use `fix/7119-apply-button-styling` branch.

If this issue is still there on branch `fix/7119-apply-button-styling` than I can look into it again 🙂

**Comment by vivialice** [comment]
@imanish003 that is the branch I was on! Convinced it is my store settings somehow 🤔

**Comment by imanish003** [comment]
@vivialice It's a weird issue to reproduce. @dinhtungdu also tried to reproduce it, but it did not reproduce for him as well. 
FYI @kmanijak has created [this PR](https://github.com/woocommerce/woocommerce-blocks/pull/7707), which also handles sizing issues.

**Comment by kmanijak** [comment]
I mentioned this issue [in this PR](https://github.com/woocommerce/woocommerce-blocks/pull/7707) (the one @imanish003 mentioned in the last comment). I merged it, so it closed this issue, but:
- it fixed misaligned padding
- it didn't fix the "rectangular vs rounded button" problem

Should I reopen the issue?
(Btw I'm reproducing rectangular vs rounded buttons, so I may take a brief look. Or @imanish003, we can try to debug together)

**Comment by imanish003** [comment]
Hey @kmanijak,
Good to know that this issue is reproducing for you 🙌🏻 

> Should I reopen the issue?

Sure, Let's reopen the issue because you are able to reproduce this issue 🤝 

> so I may take a brief look. Or @imanish003, we can try to debug together)

Sounds great! Please let me know if you want us to debug it together after taking a brief look 🙂

**Comment by gigitux** [comment]
We are planning to deprecate the mentioned filters block, so I'm going to close this issue. For more details, check out https://github.com/woocommerce/woocommerce/issues/55614
