### ISSUE TITLE
The number precision is not accurate when the last decimal digit is 0 when setting a custom precision

### ISSUE THREAD

**Issue by alopezari** [woothemes/woocommerce#46475]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

[This PR](https://github.com/woocommerce/woocommerce/pull/45743) introduced in WooCommerce 8.8 a new filter that sets a custom precision for the WC calculations.

When testing this PR, I saw everything was working good except a minor detail: When I used the `woocommerce_internal_rounding_precision` filter with precision set to `2`, I always had 2 decimals in the product price mentioned in the testing instructions except when the last decimal digit was `0`, in that case, the product price was rendered with 1 decimal instead of 2.

### Expected behavior

WooCommerce should show always prices with 2 decimals if using the `woocommerce_internal_rounding_precision` filter with precision = 2.

### Actual behavior

WooCommerce shows prices with 1 decimals if using the `woocommerce_internal_rounding_precision` filter with precision = 2 when the last decimal digit is a `0`.

### Steps to reproduce

1. Set up a site with WooCommerce 8.8.0
2. Set the option "Yes, I will enter prices inclusive of tax" under WooCommerce > Settings > Tax > Prices entered with tax:
![image](https://github.com/woocommerce/woocommerce/assets/38109855/01a23986-702c-4712-84c1-7f352c97dc94)
3. Insert a row and enter 21% as a standard tax rate (it will help to generate a price with decimals and it is also an actual tax rate in several EU countries):
![image](https://github.com/woocommerce/woocommerce/assets/38109855/adc57de4-4f8a-4cb7-9a6d-461ebe8c9164)
4. Place a new order, selecting any product. Make sure this product has such a price that when applying the 21% tax, the last decimal digit will be `0` after rounding, e.g. $21.30 or $108.40.
5. Edit the item within the order details screen, and check the decimal numbers:
![image](https://github.com/woocommerce/woocommerce/assets/38109855/341d481b-16a6-4b4a-b44b-71e73d4f0ab3)
6. Activate the following code snippet in the testing site:
```php
/**
 * WooCommerce:
 * Customize the precision value for WC calculations
 */
add_filter( 'woocommerce_internal_rounding_precision', function( $precision ) {
	return 2;
}, 10, 1 );
```
7. Place a second order, selecting the same product chosen for the first order.
8. Edit the item within the order details screen for the second order, and check the decimal numbers:
![image](https://github.com/woocommerce/woocommerce/assets/38109855/56c88d9d-d4eb-4337-85cc-45a0505dbc99)

### WordPress Environment

Any site with any WooCommerce 8.8.0 version.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
> https://github.com/woocommerce/woocommerce/pull/45743 introduced in WooCommerce 8.8 a new filter that sets a custom precision for the WC calculations.

> Any site with any WooCommerce 8.0 version.

@alopezari Should the second one be 8.8? Otherwise, how is a filter introduced in 8.8 affecting <8.8 versions?

**Comment by alopezari** [comment]
Correct, @rrennick, thanks!

It seems I wanted to write 8.8.0 so fast that I removed the '8.' in the middle 😆 

I've fixed it 🙌

**Comment by flakas** [comment]
Reviewed and confirmed this is still valid. Marking as ready for engineering.

Current evidence: Trunk still contains the formatting and precision code path that drops trailing zero precision in this scenario. A later fix commit exists for this issue, but it is not an ancestor of trunk, so the bug still appears valid against the current branch.
