### ISSUE TITLE
Release packages with node 20 compatibility

### ISSUE THREAD

**Issue by rrennick** [woothemes/woocommerce#47733]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Ref: https://github.com/woocommerce/woocommerce/issues/43034#issuecomment-2115302676

When we updated [node to v20](https://github.com/woocommerce/woocommerce/pull/45148) we should have also released updates to any npm packages that specify the node version in `package.json`. We need to create a list of those packages and release updates to any that haven't been released in the interim.

**Comment by leewillis77** [comment]
@lanej0 @rrennick This has been closed, but the issue I raised hasn't actually been resolved - it's exactly the same as it was before, so not sure what has been changed here. Some woocommerce packages still require older versions of npm.

```
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: '@woocommerce/csv-export@1.8.0',
npm warn EBADENGINE   required: { node: '^16.14.1', pnpm: '^8.6.7' },
npm warn EBADENGINE   current: { node: 'v20.14.0', npm: '10.7.0' }
npm warn EBADENGINE }
```

Here's an example `package.json` that results in that error when run with npm v20:

```json
{
  "name": "example",
  "devDependencies": {
    "@woocommerce/dependency-extraction-webpack-plugin": "^3.0"
  },
  "dependencies": {
    "@woocommerce/components": "*",
    "@woocommerce/onboarding": "*",
    "@wordpress/icons": "*",
    "@wordpress/viewport": "^*"
  }
}
```

As I noted in my previous issue, there may be other woocommerce packages that need upgrading in addition to this, but this is just an example of the issues we're hitting on one of our projects.

**Comment by lanej0** [comment]
Hi @leewillis77,

Apologies, I released a number of updated packages last week but must have missed some!  I'll take another look and make sure I've gotten as many as possible.

**Comment by lanej0** [comment]
Actually, `@woocommerce/csv-export` was one of the packages updated.  1.9.0 was released on June 11th and should have had node 20 support.  Here's the first part of the package.json from that update:

```
{
  "name": "@woocommerce/csv-export",
  "version": "1.9.0",
  "description": "WooCommerce utility library to convert data to CSV files.",
  "author": "Automattic",
  "license": "GPL-3.0-or-later",
  "engines": {
    "node": "^20.11.1",
    "pnpm": "^9.1.0"
  },
```
Are you seeing the error after updating?

**Comment by leewillis77** [comment]
Yes. You can see the error with the package.json I posted.

The issue is that packages are pulling in specific versions of dependencies. There are actually two problematic dependency chains in this examples (others may exist). 

```
$ npm why @woocommerce/csv-export
@woocommerce/csv-export@1.8.0
node_modules/@woocommerce/csv-export
  @woocommerce/csv-export@"1.8.0" from @woocommerce/components@12.3.0
  node_modules/@woocommerce/components
    @woocommerce/components@"*" from the root project
    @woocommerce/components@"12.3.0" from @woocommerce/onboarding@3.5.0
    node_modules/@woocommerce/onboarding
      @woocommerce/onboarding@"*" from the root project

@woocommerce/csv-export@1.7.0
node_modules/@woocommerce/experimental/node_modules/@woocommerce/csv-export
  @woocommerce/csv-export@"1.7.0" from @woocommerce/components@10.2.0
  node_modules/@woocommerce/experimental/node_modules/@woocommerce/components
    @woocommerce/components@"10.2.0" from @woocommerce/experimental@3.2.0
    node_modules/@woocommerce/experimental
      @woocommerce/experimental@"3.2.0" from @woocommerce/onboarding@3.5.0
      node_modules/@woocommerce/onboarding
        @woocommerce/onboarding@"*" from the root project
```

So, the issue isn't that there aren't npm v20 versions available, but that the requiring package is specifically requesting an older release.

**Comment by lanej0** [comment]
Circling back around to this, can you check out the latest version `@woocommerce/csv-export@1.9.0` and see if everything is okay now?

**Comment by leewillis77** [comment]
Hi @lanej0 ;

No - it's not. As I said in my previous reply - the issue isn't that there isn't a v20 compatible package available, but that other woo packages are pulling specific named versions which aren't compatible. The example package.json I provided in https://github.com/woocommerce/woocommerce/issues/47733#issuecomment-2175130815 still throws errors as the dependency tree causes v1.8.0 to be pulled in

**Comment by kalessil** [comment]
Removing high-prio label: based on https://nodejs.org/en/about/previous-releases, we anticipate node 22 topic to surface soon and it'll cover this issue as well.
