### ISSUE TITLE
[Enhancement]: Keeping the pricing the same regardless of the tax/VAT rate

### ISSUE THREAD

**Issue by PaddleStroke** [woothemes/woocommerce#55784]
### Describe the solution you'd like

In europe ALL shops offer a fixed price accross countries. You never see a procuct that is 3.99€ in france, then 4.24€ in Finland and 3.88€ in Germany. This is riciculous.

If a customer is from Germany for example, the VAT rate is 19%. The product cost INCLUDING taxes remains the same at 100€ for the customer, during checkout it only shows that the price of 100€ includes a tax of 19€.

If a customer is from Finland for example, the VAT rate is 24%. The product cost INCLUDING taxes remains the same at 100€ for the customer, during checkout it shows that the price of 100€ includes a tax of 24€.

*If a customer is from the United States, the VAT rate would be 0% (for a EU business that is not billing us taxes). The product should still cost 100€ for the customer, but no VAT or 0% tax will be shown on checkout.*

*It should be considered as if I did not enable taxes on my* woocommerce shop, I only did that so that they can see how much VAT/tax is included in the price during checkout.

[https://wordpress.org/support/topic/keeping-the-pricing-the-same-regardless-of-the-tax-vat-rate/](<https://wordpress.org/support/topic/keeping-the-pricing-the-same-regardless-of-the-tax-vat-rate/>)<br>[https://wordpress.org/support/topic/keeping-the-pricing-the-same-regardless-of-the-tax-vat-rate-2/](<https://wordpress.org/support/topic/keeping-the-pricing-the-same-regardless-of-the-tax-vat-rate-2/>)

### Describe alternatives you've considered

*No response*

### Additional context

*No response*

**Comment by PaddleStroke** [comment]
There is a solution that is to simply add : 
`add_filter( 'woocommerce_adjust_non_base_location_prices', '__return_false' );`

Which shows that this is actually already supported and only miss the UI.
Can someone add a 'Fix total price' checkbox in the Tax settings page? Or a combobox with 'Fix net price' and 'Fix total price'
 I don't know woocommerce source so it's going to be a pain for me to make a PR.

**Comment by jorgeatorres** [comment]
Hi @PaddleStroke,

Thanks for reaching out. We try to not to add too many options to the settings screen unless there's a good reason behind it. That said, I understand that using filters to customize behavior might be difficult for some. We're currently looking at some tax-related issues. I'm pinging @jamesckemp @dwainm for their take on this particular functionality.

Appreciate your patience.

**Comment by ResponsiveFlow** [comment]
I actually suggested the [exact same thing](https://woocommerce.com/feature-request/charge-the-same-amount-everywhere-and-absorb-the-differences-in-taxes/) on the feature request portal.

**Comment by dwainm** [comment]
Thanks for the ping @jorgeatorres , I'm taking a look at this.

**Comment by allie500** [comment]
@PaddleStroke thanks for opening this issue. Could you share some more details about your store's settings? In my test store, I am able to have prices display the same for everyone, excluding tax, regardless of location. Then VAT is calculated on the checkout page, only after they have entered their address. I created the three VAT tax rates you mentioned as standard tax rates in my test store. Below are the relevant store settings and my test store's values. Could you share yours and any other information that will help me understand your store's current setup and constraints?

* **General > Default customer location:** No location by default
* **Tax > Prices entered with tax:** No
* **Tax > Calculate tax based on:** Customer shipping address
* **Tax > Display prices in the shop:** Excluding tax
* **Tax > Display prices during cart and checkout:** Excluding tax

**German shopper checkout**

<img width="1170" height="654" alt="Image" src="https://github.com/user-attachments/assets/88f35523-f0e6-4fa2-9f0b-8b819d7fe166" />

---

**Finnish shopper checkout**

<img width="1173" height="678" alt="Image" src="https://github.com/user-attachments/assets/f8d1a2e9-8736-4568-aa1c-82c0b94fc1ba" />

---

**US shopper checkout**

<img width="1193" height="857" alt="Image" src="https://github.com/user-attachments/assets/a872f134-b72f-4edd-83dc-70f449bc2f8a" />

**Comment by PaddleStroke** [comment]
@allie500 Please read the issue description again.

>  In my test store, I am able to have prices display the same for everyone, excluding tax, regardless of location. Then VAT is calculated on the checkout page, only after they have entered their address.

This is exactly the problem. The expected behavior (in europe at least) is that the price display the same for everyone INCLUDING taxes. In europe prices are expected all taxes included. The customer do not care about the tax-excluding price in europe. It is not like in the US where taxes are not shown to the customer until checkout.

You never see a procuct that is 3.99€ in france, then 4.24€ in Finland and 3.88€ in Germany and so on.

It's crazy, woocommerce is supposed to be the #1 ecommerce solution in the world, yet it is failing on so many trivial things like this.

**Comment by PaddleStroke** [comment]
I think the missunderstanding is the difference between what is shown customers between the US and Europe. 
- In US shops always show the price excluding taxes.
- In europe law force shops to show price including taxes.

So for a customer, a '10€ product' means different things.
- US customer : think it's a 10€ product excluding taxes (he expect to pay 12€ or something)
- Europe customer : think it's a 10€ product including taxes. He expect to pay 10€ no more.

So for european shops, you set the price on your website to INCLUDE taxes (because you must by law). And in europe you advertize a product you must say the price including taxes. So you say `Look at SuperSoap the best soap at 3.99€` Then the customer, should find the product at 3.99€ independantly of his country. If he's in France, Germany, Spain, Finland... it should awlays be 3.99€ ALL TAXES INCLUDED.

Currently this is not possible with Woocommerce (well with the filter it's possible but it's buggy).

I mean we're talking about europe. It's like a very large portion of the world... It's crazy that woocommerce can't do that.

**Comment by PaddleStroke** [comment]
Maybe if you're from the US you do not realize how important this is. But for any shop manager in europe this is a huge blunder.

It is not a 'nice to have' feature. It is a 'should have been fixed after alpha release 15 years ago' problem.

This should be top priority.

**Comment by allie500** [comment]
@PaddleStroke thanks for the replies.

> The expected behavior (in europe at least) is that the price display the same for everyone INCLUDING taxes. 

This was the part that was missing. Thanks for the additional info here.

**Comment by allie500** [comment]
> Currently this is not possible with Woocommerce (well with the filter it's possible but it's buggy).

@PaddleStroke, could you share more about this? What are you finding that is buggy with the filter?

**Comment by PaddleStroke** [comment]
With the filter, creating an order manually doesn't work.
Reproduction steps : 
- Set shop to 'show price INCLUSIVE of taxes'
- Set the country of the shop as France.
- Setup european taxes (France 20%, germany 19%).
- Set the filter
- Create a 100€ product (price inclusive of taxes as you set that up before).
- Create an order
- Add the product: it appears at 80€ without taxes. 
- Add germany taxes at 19%
- BUG1 : Click recalculate : result : Germany taxes is replaced automatically by France taxe: 80€ + 20€ taxes = 100€

- start over. This time enter a billing address in Germany first (this fixes BUG1).
- Add the product
- Add the product: it appears at 80€ without taxes. 
- Add germany taxes at 19%
- BUG 2 : Click recalculate : Taxes stay 19% but the calculus is based on 80€. So total is not 100€ ! It is 98.xx€.

**Comment by ebinnion** [comment]
Hello @PaddleStroke  - I've deployed a fix for the bugs with manual order creation in #62271. This is due to ship in WooCommerce 10.5.0 on February 3rd, but will be available in beta from January 19th. 

https://developer.woocommerce.com/release-calendar/

Thank you for the bug report and your feedback.

**Comment by PaddleStroke** [comment]
Thanks for tackling this !

**Comment by PaddleStroke** [comment]
The issue should not be marked as completed. Only the bug described in the above comment has been fixed.
The main topic of the ticket has not been addressed.
Please reopen the ticket @ebinnion

**Comment by PaddleStroke** [comment]
bump @ebinnion this should not have been closed... woocommerce tend to close issues even when they are not fixed just to clean the stack of issue. This is ridiculous that doesn't make the problem go away.
