### ISSUE TITLE
Pagination does not work on WordPress.com on WP Cloud websites with Gutenberg 20.0.4

### ISSUE THREAD

**Issue by arunsathiya** [woothemes/woocommerce#57171]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I am seeing an issue with pagination on product templates not working, but this is happening only on WordPress.com on WP Cloud websites, with Twenty Twenty-Four and Twenty Twenty-Five themes. There are likely a few other themes that are affected, but these are what I tested with so far.

The pagination links appear, but clicking on them does not respond.

<img width="1550" alt="Image" src="https://github.com/user-attachments/assets/c09d1db5-e564-40f9-ae19-892a512aab7c" />

<img width="1696" alt="Image" src="https://github.com/user-attachments/assets/b5131c97-7668-452d-89bc-d3cd526c7e2b" />

**Edit to note**: the issue **does not happen on Storefront**, both with and without [infinite scrolling, which is a Jetpack feature](https://jetpack.com/support/infinite-scroll/).

### Expected behavior

The pagination links should respond upon click.

### Actual behavior

The links appear, but clicking on them does not respond.

### Steps to reproduce

- Setup a WordPress.com on WP Cloud site from https://wordpress.com/start (Business plan or Commerce plan)
- Install Woo and import sample products.
- Update `Products by category` or `Product catalog` template to show 2 products per page. (although, the number of products don't matter)
- Click on the pagination links, notice that they don't respond.

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.8.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.2
Log Directory Writable: ✔
WP Version: 6.7.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.2.28
PHP Post Max Size: 2 GB
PHP Time Limit: 850
PHP Max Input Vars: 6144
cURL Version: 8.12.1
OpenSSL/3.0.15

SUHOSIN Installed: –
MySQL Version: 10.11.11-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 24
page: 6
post: 4
product: 18
product_variation: 7
revision: 2
wp_global_styles: 2
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (8) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.7
Crowdsignal Forms: by Automattic – 1.7.2
Gutenberg: by Gutenberg Team – 20.0.4
Jetpack: by Automattic – 14.6-a.1
Layout Grid: by Automattic – 1.8.5
Page Optimize: by Automattic – 0.5.6
Crowdsignal Polls & Ratings: by Automattic
Inc. – 3.1.2

WooCommerce: by Automattic – 9.8.1

### Inactive Plugins (1) ###

Classic Editor: by WordPress Contributors – 1.6.7

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

wpcomsh-loader.php: by  –

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 743 B

### WC Pages ###

Shop base: #11 - /shop/
Cart: #12 - /cart/ -  Contains the woocommerce/cart block
Checkout: #13 - /checkout/ -  Contains the woocommerce/checkout block
My account: #14 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Five
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /wordpress/plugins/woocommerce/9.8.1/templates/block-notices/error.php
/wordpress/plugins/woocommerce/9.8.1/templates/block-notices/notice.php
/wordpress/plugins/woocommerce/9.8.1/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store
add-to-cart-with-options-stepper-layout

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon
blockified-add-to-cart

Daily Cron: ✔ Next scheduled: 2025-04-11 15:04:29 +05:30
Options: ✔
Notes: 59
Onboarding: skipped

### Action Scheduler ###

Complete: 126
Oldest: 2025-04-10 20:34:32 +0530
Newest: 2025-04-11 13:24:21 +0530

Failed: 1
Oldest: 2025-04-11 13:16:33 +0530
Newest: 2025-04-11 13:16:33 +0530

Pending: 1
Oldest: 2025-04-11 20:35:41 +0530
Newest: 2025-04-11 20:35:41 +0530


### Status report information ###

Generated at: 2025-04-11 13:30:34 +05:30
```
</details>

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by arunsathiya** [comment]
I see this on the browser console, and a reference to a similar error [here](https://github.com/woocommerce/woocommerce/pull/56154#issuecomment-2703595903). 
```
Uncaught (in promise) TypeError: Cannot destructure property 'animationStatus' of 's(...)' as it is undefined.
```

**Comment by arunsathiya** [comment]
Additional note: The issue does not happen on Storefront, both with and without [infinite scrolling, which is a Jetpack feature](https://jetpack.com/support/infinite-scroll/).

**Comment by arunsathiya** [comment]
Another note of clarity: This is happening only on WordPress.com based websites. This is not happening on a different hosting platform.

**Comment by hacchism** [comment]
Hi @arunsathiya👋

I had a similar report with a different theme (**Aether**) - 9647392-zen

I conducted some tests, and from what I found, I believe this is a conflict issue with Gutenberg 20.0.4 (the current version of symlinked Gutenberg) and the [Product Collection](https://woocommerce.com/document/woocommerce-store-editing/customizing-shop-page-catalog/product-collection-block/) Block.

If I unsymlink Gutenberg and update it to the latest version (20.6.0), the issue goes away.

We shouldn't be able to reproduce this issue on Storefront because Storefront isn't a FSE theme (meaning it doesn't use the Product Collection Block for a shop template).

The workaround is either deactivating Gutenberg or unsymlinking it.

**Comment by arunsathiya** [comment]
Great find, thank you, @hacchism! I've reached out to my customer in 9638243-zen to discuss this fix. I think I can close the issue because the issue can be reproduced only on an outdated version of Gutenberg, but I'll leave the issue open for a bit, for maintainers to decide if it's worth closing it.

**Comment by khristiansnyder** [comment]
Came across this today as well in #9652297-zen. Deactivated Gutenberg for now to bypass the issue.  The theme is Assembler.

**Comment by adelineyaw** [comment]
User came into chat with this issue 9653256-zd-a8c Theme: Twenty Twenty Four. Deactivated Gutenberg for now to bypass the issue.

**Comment by ahmadbaig1** [comment]
#9648126-zen, same issue. This issue does not seem to be theme-related. It's directly related to the Gutenberg plugin.

**Comment by gigitux** [comment]
Thanks for your report! This issue should now be resolved with the WordPress 6.8 release on WordPress.com. I'm closing this ticket, but please let us know if you encounter this error again.

**Comment by arunsathiya** [comment]
Thank you. Just to clarify though, can users with affected Gutenberg version 20.0.4 remain on the same version?

**Comment by gigitux** [comment]
> Thank you. Just to clarify though, can users with affected Gutenberg version 20.0.4 remain on the same version?

Technically, WordPress 6.8 is shipped with a more recent Gutenberg release. You can read more about it: pgle0O-6a-p2#comment-325

**Comment by arunsathiya** [comment]
@gigitux Good to know. Thanks for the details. Although under these conditions, I am still seeing the issue: Gutenberg 20.0.4 + WordPress.com on WP Cloud (Atomic site) + WordPress 6.8. Is the direction from Woo that the hosting provider should update Gutenberg to the latest version? Or would there be interest from Woo's side to fix this issue with the older version of Gutenberg (20.0.4) as well?

**Comment by gigitux** [comment]
> [@gigitux](https://github.com/gigitux) Good to know. Thanks for the details. Although under these conditions, I am still seeing the issue: Gutenberg 20.0.4 + WordPress.com on WP Cloud (Atomic site) + WordPress 6.8. Is the direction from Woo that the hosting provider should update Gutenberg to the latest version? Or would there be interest from Woo's side to fix this issue with the older version of Gutenberg (20.0.4) as well?

Maybe @luisherranz you have a different opinion, but given that Gutenberg 20.0.4 is an outdated version of Gutenberg, I don't think that we will fix it on the Woo side.

I think that the options are two:
- update Gutenberg.
- disable Gutenberg plugin, given that WordPress 6.8 is shipped with a more recent release of Gutenberg.

**Comment by Greatdane** [comment]
9678562-zd-a8c - I installed Gutenberg 20.6.0 and it fixed the issue.

**Comment by hacchism** [comment]
Just adding that Gutenberg on Atomic has been updated to v20.6.0, so it should be safe to reactivate Gutenberg now on all the affected sites.
