### ISSUE TITLE
Analytics bug for product sales count.

### ISSUE THREAD

**Issue by Bsavage20** [woothemes/woocommerce#60097]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using the analytics for products, when you search for a single product to see what your sales have been by using the filter, if there is more than one item on the invoice, it's pulling the total number of items sold on that invoice (which is useless info)  instead of just the one product you are trying to get a global sales count for.  It's over inflating your sales.

### Expected behavior

You should only get the number of that products sales.  

### Actual behavior

see above

### Steps to reproduce

see image

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 10.0.4
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.2
Log Directory Writable: ✔
WP Version: 6.8.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en
External object cache: –

### Server Environment ###

Server Info: Apache
Server Architecture: Linux 4.18.0-553.54.1.lve.el8.x86_64 x86_64
PHP Version: 8.4.8
PHP Post Max Size: 128 MB
PHP Time Limit: 3000
PHP Max Input Vars: 1000
cURL Version: 8.14.1
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.22-MariaDB-cll-lve
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

acf-field: 3
acf-field-group: 1
af_c_fields: 3
af_ch_fields: 1
attachment: 647
b2bking_custom_field: 10
b2bking_custom_role: 3
b2bking_group: 2
b2bking_rule: 15
b2bwhs_custom_field: 10
b2bwhs_custom_role: 2
b2bwhs_group: 2
b2bwhs_list: 1
b2bwhs_rule: 3
custom_css: 1
customize_changeset: 1
def_reg_fields: 10
feedback: 63
mailpoet_page: 2
nav_menu_item: 30
oembed_cache: 8
page: 53
post: 24
product: 54
product_variation: 29
rcbp-rule: 10
revision: 143
shop_order: 1174
shop_order_refund: 53
shopmagic_list: 2
ticket: 1015
ticket_history: 2470
ticket_log: 13
ticket_note: 120
ticket_reply: 3429
wc_conditional_fee: 1
wc_membership_plan: 2
wc_order_status: 21
wc_user_membership: 1
wp_global_styles: 1
wp_navigation: 1
wp_template: 2
wpi_payment_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (48) ###

Custom Fields for WooCommerce: by Addify – 1.4.0
Advanced Custom Fields PRO: by WP Engine – 6.4.2
Advanced Order Notes for WooCommerce: by wpexperts – 1.0
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.5
All-in-One WP Migration Dropbox Extension: by ServMask – 3.93
All-in-One WP Migration and Backup: by ServMask – 7.97
Awesome Support: Custom Fields: by The Awesome Support Team – 2.0.1
Awesome Support: Gravity Forms: by Awesome Support – 1.5.4
Awesome Support: Private Notes: by The Awesome Support Team – 3.5.1
Awesome Support: WooCommerce: by Awesome Support Team – 1.5.2
Awesome Support: by Awesome Support Team – 6.3.4
B2BKing Pro: by WebWizards – 5.3.40
B2BKing Core: by WebWizards – 4.9.10
Code Snippets: by Code Snippets Pro – 3.6.8
Customize My Account Page For Woocommerce: by WPEverest – 1.0.1 (update to version 1.0.2 is available)
Folders: by Premio – 3.1.2
Gravity Forms: by Gravity Forms – 2.9.11
Gravity Forms Polls Add-On: by Gravity Forms – 4.3.0
Gravity Forms Quiz Add-On: by Gravity Forms – 4.3.0
Gravity Forms User Registration Add-On: by Gravity Forms – 5.4.0
Jetpack: by Automattic – 14.8
Jetpack CRM Extension: Awesome Support Connector: by Automattic – 2.6.2
Jetpack CRM Extension: Client Portal Pro: by Automattic – 2.2.2
Login as User Pro: by Web357 – 1.6.1
Manage Notification E-mails: by Virgial Berveling – 1.8.6
Members: by MemberPress – 3.2.18
Omnisend for WooCommerce: by Omnisend – 1.16.7
Default WooCommerce Shipping Method addon: by PluginHive – 2.0.0
Woocommerce Partial Shipment: by WpExperts Hub – 3.3
Product Gallery Slider & Additional Variation Images for WooCommerce: by Codeixer – 2.3.21
Payment Plugins for Stripe WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.3.91

WooCommerce.com Update Manager: by Automattic – 1.0.3
Print Invoice & Delivery Notes for WooCommerce: by Tyche Softwares – 5.7.0
GDPR Cookies: by OPMC – 1.3.2
Multi-Carrier Shipping Plugin for WooCommerce: by PluginHive – 3.0.8
Advanced Order Export For WooCommerce (Pro): by AlgolPlus – 4.0.3
WooCommerce Order Status Manager: by SkyVerge – 1.15.6
WooCommerce Product Search: by itthinx – 6.7.0
WooCommerce: by Automattic – 10.0.4
Wordfence Security: by Wordfence – 8.0.5
WP File Manager - PRO: by mndpsingh287 – 8.4.3
WP Mail Logging: by WP Mail Logging Team – 1.14.0
WP Mail SMTP: by WP Mail SMTP – 4.5.0
WP-Optimize - Clean, Compress, Cache: by TeamUpdraft
DavidAnderson – 4.2.3

Advance Partial Shipment for woocommerce: by WpExperts Hub – 2.6.1
Partial Shipment Migration Addon: by WpExperts Hub – 1.3
Sequential Order Numbers for WooCommerce: by WebToffee – 1.7.2
Jetpack CRM: by Automattic - Jetpack CRM team – 6.6.1

### Inactive Plugins (10) ###

Debug Log Manager Tool: by Lukman Nakib – 2.0.1
Download Plugin: by Download Plugin – 2.2.9
Enhanced User Search: by Shabnam – 1.0.0
Gutena Forms - Contact Forms Block: by ExpressTech – 1.2.7
Limit Login Attempts Reloaded: by Limit Login Attempts Reloaded – 2.26.19
Login as User: by Web357 – 1.6.1
Password Protect WordPress Lite: by BWPS – 1.9.12
Role and Customer Based Pricing by Meow Crew: by Meow Crew – 1.6.4
WooCommerce Memberships: by SkyVerge – 1.27.2
WooCommerce Tax: by WooCommerce – 3.0.7

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (2) ###

Awesome Support – User Picker: Email, Username, Name Search: by Your Name – 1.0
WordPress automation by Installatron: by  –

### Settings ###

Legacy API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔
Enabled Features: analytics
marketplace
order_attribution
site_visibility_badge
remote_logging
email_improvements
blueprint
point_of_sale
custom_order_tables


### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 64 MB

### WC Pages ###

Shop base: #2594 - /shop/
Cart: #9 - /cart-2/ -  Contains the woocommerce_cart shortcode
Checkout: #10 - /checkout/ -  Contains the woocommerce_checkout shortcode
My account: ❌ Page does not contain the [woocommerce_my_account] shortcode.
Terms and conditions: #501 - /terms-and-conditions/

### Theme ###

Name: Olymp
Version: 1.1.3
Author URL: https://vivathemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Classic theme
WooCommerce Support: ✔

### Templates ###

Overrides: olymp/woocommerce/myaccount/form-login.php
/home/kndkyzh85jw3/public_html/shop.kollectfun.com/wp-content/plugins/woo-product-gallery-slider/includes/product-image.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store
add-to-cart-with-options-stepper-layout

Disabled Features: product-data-views
experimental-blocks
experimental-iapi-mini-cart
experimental-iapi-runtime
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon

Daily Cron: ✔ Next scheduled: 2025-07-30 15:26:19 -06:00
Options: ✔
Notes: 53
Onboarding: completed

### Action Scheduler ###

Complete: 95,636
Oldest: 2025-06-29 02:08:21 +0000
Newest: 2025-07-30 02:07:48 +0000

Failed: 5,593
Oldest: 2023-10-05 16:23:23 +0000
Newest: 2025-07-08 00:48:53 +0000

Pending: 12
Oldest: 2025-07-30 02:09:07 +0000
Newest: 2025-08-04 20:28:13 +0000


### Status report information ###

Generated at: 2025-07-29 20:07:56 -06:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by nerrad** [comment]
Hi there, you mentioned "see image" in the issue but there is no link (or image). It will be helpful to understand specifically what analytics you are referring to.

**Comment by Bsavage20** [comment]
[Screenshot 2025-07-29 at 9.06.11 PM.png]

I attached the image of the filter analytics I thought.  It’s counting items on that invoice not just the specific product.

Thanks,


Brian Savage

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error, please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee, you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient, you are notified that disclosing, copying, distributing, or taking any action in reliance on the contents of this information is strictly prohibited.

On Jul 30, 2025, at 2:02 AM, Darren Ethier ***@***.***> wrote:

[https://avatars.githubusercontent.com/u/1429108?s=20&v=4]nerrad left a comment (woocommerce/woocommerce#60097)<https://github.com/woocommerce/woocommerce/issues/60097#issuecomment-3135095602>

Hi there, you mentioned "see image" in the issue but there is no link (or image). It will be helpful to understand specifically what analytics you are referring to.

**Comment by nerrad** [comment]
Hi there, I see you sent a reply via email. It didn't include the image. Unfortunately, there's still not enough information for me to understand what you are reporting.

**Comment by nerrad** [comment]
I'm going to close this issue because there isn't anything actionable. When there is additional information that can help us understand what is going wrong (and how to reproduce) we'll look at addressing.

**Comment by Bsavage20** [comment]
I’m confused as to what you want l.  It’s pretty simple, your report mis counts products that are sold.  It’s counting the number of items on that invoice, not the number of that specific product.  What do you need?

Brian
Sent from my iPhone

On Aug 6, 2025, at 8:10 AM, Darren Ethier ***@***.***> wrote:

﻿
[https://avatars.githubusercontent.com/u/1429108?s=20&v=4]nerrad left a comment (woocommerce/woocommerce#60097)<https://github.com/woocommerce/woocommerce/issues/60097#issuecomment-3160116117>

I'm going to close this issue because there isn't anything actionable. When there is additional information that can help us understand what is going wrong (and how to reproduce) we'll look at addressing.

**Comment by nerrad** [comment]
There still is not a usable image visible on this GitHub issue. Which could help with understanding:

* What specific report you are referring to.
* What filter you are referring to.

I'm interested in helping figure out what might be happening in your case, but I don't have enough information.

**Comment by Bsavage20** [comment]
This filter picking out a single product or multiple products.

See product includes 2 items?

Thanks,

Brian

[Screenshot 2025-07-29 at 9.06.11 PM.png]
Brian Savage

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error, please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee, you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient, you are notified that disclosing, copying, distributing, or taking any action in reliance on the contents of this information is strictly prohibited.

On Aug 6, 2025, at 10:02 AM, Darren Ethier ***@***.***> wrote:

[https://avatars.githubusercontent.com/u/1429108?s=20&v=4]nerrad left a comment (woocommerce/woocommerce#60097)<https://github.com/woocommerce/woocommerce/issues/60097#issuecomment-3160542978>

There still is not a usable image visible on this GitHub issue. Which could help with understanding:

  *   What specific report you are referring to.
  *   What filter you are referring to.

I'm interested in helping figure out what might be happening in your case, but I don't have enough information.

**Comment by nerrad** [comment]
What you may not be realizing is that Github does not show attached content when replies to issues are sent via email. So while you may be seeing the image in your email client, it is not displayed on the actual issue in GitHub. All I see is this:

```
[Screenshot 2025-07-29 at 9.06.11 PM.png]
```

You'll have to visit the issue via the GitHub UI to add the image. Thanks.

**Comment by Bsavage20** [comment]
<img width="1640" height="815" alt="Image" src="https://github.com/user-attachments/assets/469c8367-b73a-4da7-a2fc-5eafb6ff22ac" />

**Comment by Bsavage20** [comment]
Update?

**Comment by chihsuan** [comment]
Hi @Bsavage20 I appreciate you providing the screenshots. That really helps!

I want to make sure I understand the behavior you're experiencing correctly. I was able to reproduce the issue on my side by following these steps:

1. Create two products with different prices
2. Create an order that includes both products
3. Navigate to `Analytics > Orders`
4. Filter by one specific product
5. Observe that the report shows metrics for the entire order (including all items), not just the filtered product

<img width="1252" height="592" alt="Image" src="https://github.com/user-attachments/assets/4a51eabc-354b-4f34-aaad-d8b028730210" />

Is this accurate?

---

If so, the behavior you're observing in `Analytics > Orders` is acutally expected. This page is designed to provide order-level analytics. When you filter by a product, it shows metrics for every order containing that product, including the complete order totals and item counts.

For product-specific metrics (showing only data related to the individual product you're interested in), you'll want to use `Analytics > Products` instead. 

**Question**
Is there a specific use case or workflow where you need this product-specific data to be available on the Orders page rather than using the Products analytics page? Understanding your needs would help us evaluate if any enhancements might be beneficial.

**Comment by Bsavage20** [comment]
Yes but if I remember correctly it is counting all items on the invoice as that products sales.  Like you may have one of the item you are searching for but if you have 3 other items on the same invoice, it shows you a count of 4 sales, not 1.

Woo really falls down on the sales reporting.  It should be also on your product inventory screen. It should also have amount sold and amount still in inventory.

Thanks,

Brian Savage

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error, please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee, you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient, you are notified that disclosing, copying, distributing, or taking any action in reliance on the contents of this information is strictly prohibited.

On Aug 13, 2025, at 4:14 AM, Chi-Hsuan Huang ***@***.***> wrote:

[https://avatars.githubusercontent.com/u/4344253?s=20&v=4]chihsuan left a comment (woocommerce/woocommerce#60097)<https://github.com/woocommerce/woocommerce/issues/60097#issuecomment-3182899459>

Hi @Bsavage20<https://github.com/Bsavage20> I appreciate you providing the screenshots. That really helps!

I want to make sure I understand the behavior you're experiencing correctly. I was able to reproduce the issue on my side by following these steps:

  1.  Create two products with different prices
  2.  Create an order that includes both products
  3.  Navigate to Analytics > Orders
  4.  Filter by one specific product
  5.  Observe that the report shows metrics for the entire order (including all items), not just the filtered product

Screenshot.2025-08-13.at.17.07.21.png (view on web)<https://github.com/user-attachments/assets/4a51eabc-354b-4f34-aaad-d8b028730210>

Is this accurate?

________________________________

If so, the behavior you're observing in Analytics > Orders is acutally expected. This page is designed to provide order-level analytics. When you filter by a product, it shows metrics for every order containing that product, including the complete order totals and item counts.

For product-specific metrics (showing only data related to the individual product you're interested in), you'll want to use Analytics > Products instead.

Question
Is there a specific use case or workflow where you need this product-specific data to be available on the Orders page rather than using the Products analytics page? Understanding your needs would help us evaluate if any enhancements might be beneficial.

**Comment by chihsuan** [comment]
> Yes but if I remember correctly it is counting all items on the invoice as that products sales.  Like you may have one of the item you are searching for but if you have 3 other items on the same invoice, it shows you a count of 4 sales, not 1.
> 
> Woo really falls down on the sales reporting.  It should be also on your product inventory screen. It should also have amount sold and amount still in inventory.
> 

@Bsavage20 I can confirm that the behavior in `Analytics > Orders` is indeed counting all items on the invoice as sales for the filtered product. But this's expected behavior, as the report is designed to show order-level metrics. 

If you're looking for product-level sales data, you can navigate to `Analytics > Products`, where you’ll see a breakdown of sales for each product and its inventory status. 

For example,  during our test, I placed an order containing two products.

<img width="1419" height="794" alt="Image" src="https://github.com/user-attachments/assets/d09c96e3-6041-4b5a-b1c5-0afccc71a2af" />

In the product analytics report, I applied a filter for Product 1. It shows that only 3 units were sold, with $30 in net sales. This reflects the sales for that specific product, not the total items on the invoice.


<img width="1913" height="926" alt="Image" src="https://github.com/user-attachments/assets/02d7f72e-c352-4259-b9a7-fa7404084339" />


Let us know if you visit `Analytics > Products`, all items on the invoice are still being counted as sales for the filtered product, or if we've misunderstood anything.

Thanks!

**Comment by Bsavage20** [comment]
Thanks,

The product is a better search but on the invoices when you filter by product telling how many items in the order is pretty useless.

Thanks,

Brian Savage

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error, please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee, you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient, you are notified that disclosing, copying, distributing, or taking any action in reliance on the contents of this information is strictly prohibited.

On Aug 13, 2025, at 9:26 PM, Chi-Hsuan Huang ***@***.***> wrote:

[https://avatars.githubusercontent.com/u/4344253?s=20&v=4]chihsuan left a comment (woocommerce/woocommerce#60097)<https://github.com/woocommerce/woocommerce/issues/60097#issuecomment-3186536038>

Yes but if I remember correctly it is counting all items on the invoice as that products sales. Like you may have one of the item you are searching for but if you have 3 other items on the same invoice, it shows you a count of 4 sales, not 1.

Woo really falls down on the sales reporting. It should be also on your product inventory screen. It should also have amount sold and amount still in inventory.

@Bsavage20<https://github.com/Bsavage20> I can confirm that the behavior in Analytics > Orders is indeed counting all items on the invoice as sales for the filtered product. But this's expected behavior, as the report is designed to show order-level metrics.

If you're looking for product-level sales data, you can navigate to Analytics > Products, where you’ll see a breakdown of sales for each product and its inventory status.

For example, during our test, I placed an order containing two products.

Screenshot.2025-08-14.at.10.14.36.png (view on web)<https://github.com/user-attachments/assets/d09c96e3-6041-4b5a-b1c5-0afccc71a2af>

In the product analytics report, I applied a filter for Product 1. It shows that only 3 units were sold, with $30 in net sales. This reflects the sales for that specific product, not the total items on the invoice.

Screenshot.2025-08-14.at.10.19.39.png (view on web)<https://github.com/user-attachments/assets/02d7f72e-c352-4259-b9a7-fa7404084339>

Let us know if you visit Analytics > Products, all items on the invoice are still being counted as sales for the filtered product, or if we've misunderstood anything.

Thanks!

**Comment by chihsuan** [comment]
> The product is a better search but on the invoices when you filter by product telling how many items in the order is pretty useless.

Hi Brian, thank you for your feedback.

Order Analytics is designed to show order-level information (total items per order, order values, etc.), which is why filtering by product still shows total order quantities. I understand that this might not be what you’re looking for when filtering by product, but it’s acutally the intended behavior for order analysis. Order Analytics is designed to show order information. The filters are only there to help you narrow down the orders you’re looking at.

If you're looking for product-level details, you might want to use the Product Analytics section. Is there a particular reason you prefer using Order Analytics to track the number of items sold per product instead of Product Analytics?

**Comment by Bsavage20** [comment]
Yes, because we have an item that we sell at full price and when the in stock is gone we take a deposit on the item.  That’s the same item and I prefer a complete count of what has been sold.  Also, I have always thought it was odd that when you look at a products inventory page there is no sold amount.

Thanks,

Brian Savage

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error, please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee, you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient, you are notified that disclosing, copying, distributing, or taking any action in reliance on the contents of this information is strictly prohibited.

On Aug 14, 2025, at 11:35 PM, Chi-Hsuan Huang ***@***.***> wrote:

[https://avatars.githubusercontent.com/u/4344253?s=20&v=4]chihsuan left a comment (woocommerce/woocommerce#60097)<https://github.com/woocommerce/woocommerce/issues/60097#issuecomment-3190585798>

The product is a better search but on the invoices when you filter by product telling how many items in the order is pretty useless.

Hi Brian, thank you for your feedback.

Order Analytics is designed to show order-level information (total items per order, order values, etc.), which is why filtering by product still shows total order quantities. I understand that this might not be what you’re looking for when filtering by product, but it’s acutally the intended behavior for order analysis. Order Analytics is designed to show order information. The filters are only there to help you narrow down the orders you’re looking at.

If you're looking for product-level details, you might want to use the Product Analytics section. Is there a particular reason you prefer using Order Analytics to track the number of items sold per product instead of Product Analytics?

**Comment by chihsuan** [comment]
Hi @briansavage,

Thank you for confirming the behavior and sharing your perspective on this! 

You can find product-specific data on the Products analytics page, although I realize this might not align exactly with your current workflow. This appears to be a feature request rather than a bug, so I'll update the issue labels accordingly.

**Comment by chihsuan** [comment]
@briansavage, Following team discussions, we decided not to move forward with this feature. The `Analytics > Orders page` is specifically designed to show order metrics. While the filters on order analytics allow users to filter orders by different criteria, they do not impact the sales count.

I'll close this issue. If you find `Analytics > Products` not meeting your needs, please feel free to open a new feature request. Thanks!

**Comment by nerrad** [comment]
> …open a new feature request

Just a note, that feature requests should be done via the [WooCommerce feature requests board](https://woocommerce.com/feature-requests/woocommerce/).
