### ISSUE TITLE
Incorrect term count when calling get_term() instead of get_terms()

### ISSUE THREAD

**Issue by Aljullu** [woothemes/woocommerce#61452]
## **Describe the bug**

WooCommerce hooks into `get_terms` to update the product-related taxonomy counts to account for hierarchical categories and products being hidden from the catalog:

[https://github.com/woocommerce/woocommerce/blob/56aedb6ba42f85302daa50f1f5415ff262daa007/plugins/woocommerce/includes/wc-term-functions.php#L616](https://github.com/woocommerce/woocommerce/blob/56aedb6ba42f85302daa50f1f5415ff262daa007/plugins/woocommerce/includes/wc-term-functions.php#L616)

However, WooCommerce doesn't hook in the same way into `get_term`. That causes inconsistent results.

That can be reproduced in the *Term Count* block currently in development in Gutenberg (see [https://github.com/WordPress/gutenberg/issues/72363](https://github.com/WordPress/gutenberg/issues/72363)): it calls `get_terms()` in the editor and `get_term()` in the frontend, so term counts are different.

## **To Reproduce**

* Install Gutenberg 21.8 or later, enable the experimental blocks.
* Add the *Terms Query* block to a post or page and select *Product category* as the taxonomy to display.
* Notice the totals are different in the editor and the frontend.
  * That's assuming you have hierarchical categories or at least one product hidden from the catalog.

## **Expected behavior**

The totals in the frontend should match the ones in the editor (which are correct). In other words, `get_term()` should return the correct `count`.

## **Screenshots**

<img src="https://uploads.linear.app/f629fcde-6f9b-48e8-8af3-60eed8823bff/4c2af5d0-47d0-49f6-8d34-9d712e69e87f/d50c50f6-4f01-44d9-b8a1-8ef2e60ddb1f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y2MjlmY2RlLTZmOWItNDhlOC04YWYzLTYwZWVkODgyM2JmZi80YzJhZjVkMC00N2QwLTQ5ZjYtOGQzNC05ZDcxMmU2OWU4N2YvZDUwYzUwZjYtNGYwMS00NGQ5LWI4YTEtOGVmMmU2MGRkYjFmIiwiaWF0IjoxNzYwNTM5NTA2LCJleHAiOjMzMzMxMDk5NTA2fQ.JRnc2Z4j8BCzZ_d0w2CGTUY1pIRlFnsv9oB8dXMPdH0 " alt="501550808-fad24d71-751c-4f8e-9369-0b1ef9a7b58c.png" width="847" data-linear-height="497" />

The *Product Categories List* shows the correct totals in the frontend, while the *Terms Query* doesn't: *Clothing* should be `14` and *Hoodies* should be `4`.

**Comment by prettyboymp** [comment]
Do we still need to keep the original term count for WooCommerce taxonomies?  

There is a bit of overhead added by counting the terms twice (WP's default and WC specific) on updates and additional overhead when rendering terms to replace the counts for output.

I'm not sure how easy it can be done due to backward compatibility. 🤔

**Comment by Aljullu** [comment]
I hadn't put a lot of thinking into it yet, but in my mind we would do in `get_term` exactly the same as we do in `get_terms`, which, if I'm not wrong, means replacing the `count` property. I'm not sure about the impact on backward compatibility, but the current behavior where `get_terms()` and `get_term()` return different counts feels buggy to me.

**Comment by sunyatasattva** [comment]
Did I recall correctly that @dinhtungdu had similar issues when developing the filters?

**Comment by dinhtungdu** [comment]
@sunyatasattva I don't think that was the same issue. For filter, I had to use custom SQL queries and product lookup tables to count the product because we need to take other applied filters into account.

**Comment by sunyatasattva** [comment]
What do you folks think about the best way of proceeding here is? I definitely agree with what @Aljullu said about the behavior, but am wary of changing it because of backwards compatibility. Does anyone have more experience with working with this function?

**Comment by Aljullu** [comment]
I'm not very experienced with this part of the codebase, unfortunately. Having said that, the current behavior is already causing issues with the _Terms Query_ block in Gutenberg, and IMO it's clearly a bug/inconsistency in WC core that needs to be fixed. So I lean towards fixing it and making things work well with WordPress core.

In order to minimize risk, we could publish a developer advisory and audit existing extensions that call `get_term()`?

**Comment by sunyatasattva** [comment]
I agree that this is a problem and should be fixed. Whether people “relied” on this problem or not, is the issue. I guess a revert is always on the table, and we can try to go the bold route.

**Comment by prettyboymp** [comment]
@mikejolley Do yo have any insight into why alternate term counts for Woo taxonomies are stored in term meta rather than using the term count directly?  I feel like this was working around an issue with older versions of WP that are no longer supported, but wasn't sure.<br><br>I know we'll need to consider extension compatibility if we change where this is stored, but I wanted to check there wasn't another existing reason we would need to keep calculating and storing the modified term count separately.

**Comment by mikejolley** [comment]
@prettyboymp from memory its to do with hierarchy—term counts count things assigned to the term directory. Woo term counts count things assigned to the term and its children.

**Comment by kkoteen** [comment]
Hi @Aljullu - can you provide an update or next steps here? Thanks!

**Comment by Aljullu** [comment]
The issue is still reproducible. As @mikejolley said above, WC core handles term counts differently from WP core, the issue is that this custom behavior was only applied to `get_terms()` and not `get_term()`, which is confusing because then the results from the two functions differ. In the _Term Count_ block from Gutenberg this manifest by having different values in the frontend and the editor.

I don't think we can change the WC core behavior at this point, so I would update `get_term()` to behave like `get_terms()`, even though that adds a bit overhead because we are counting the children twice as @prettyboymp said.

So IMO the next step is that engineering can pick this up and update `get_term()` to behave like `get_terms()`, but happy if somebody has any other ideas. 🙂
