### ISSUE TITLE
Tax shows "0" although setup correctly

### ISSUE THREAD

**Issue by Haabster** [woothemes/woocommerce#8147]
When setting up taxes, the tax in the shop is always shown as "0", even when tax is setup correctly. 

This happens with WooCommerce 2.3.8 on wordpress 4.2.2. Reproduction seems to need a clean install of WordPress and WooCommerce (see https://wordpress.org/support/topic/woocommerce-taxes-not-working-correctly and https://wordpress.org/support/topic/tax-not-working-tax-always-equals-0). 

Please let me know if any additional information is needed. 

So far, I found tax settings in the database table "0_woocommerce_tax_rates". 
![image](https://cloud.githubusercontent.com/assets/12409624/7585277/8b34ce1c-f8a3-11e4-915b-c7e29a609606.png)

Additional screenshots of the applied tax settings: 
![product-description](https://cloud.githubusercontent.com/assets/12409624/7585298/98c21dfa-f8a3-11e4-895f-cdff56ebd516.PNG)
![tax-rates](https://cloud.githubusercontent.com/assets/12409624/7585296/98bfb1aa-f8a3-11e4-98cb-31ddfde1c3f4.PNG)
![tax-settings](https://cloud.githubusercontent.com/assets/12409624/7585297/98bffaa2-f8a3-11e4-98ae-c2cebd88d259.PNG)

**Comment by mikejolley** [comment]
I just mirrored your settings exactly and I get taxes:

https://dl.dropboxusercontent.com/s/dr4sgyvkpryaua2/2015-05-13%20at%2014.22%202x.png?dl=0

What is your base country and 'Default Customer Address'?

**Comment by Haabster** [comment]
Thanks for your effort! The shop base country is "Netherlands", and the Default Customer Address is "Shop base Address" (if I am translating that correctly). 

Did you try this on a fresh installation? It only seems to happen on "new" systems.

**Comment by jkriester** [comment]
Can confirm! I have exact same problem. On old installations I get calculated tax but on new installation with exact same settings tax is not calculated. 

Also this note seems to be gone: "Note: Shipping and taxes are estimated and will be updated during checkout based on your billing and shipping information".

I guess this is related to the current work on the cart.php I see in the woon changelog.
But a rollback to a previous version also does not seem to solve the problem.

:(

**Comment by mikejolley** [comment]
I've no issues clean install locally. Has to be setup related; if you email a login to mike.j@woothemes.com I'll take a quick look at what you have installed.

**Comment by Haabster** [comment]
Dear Mike,

If everything went allright, you have just received a login to the website
projecth.nl. This is regarding the bug reported on github with number
#8147. If there's anything else you need to know, please let me know so I
can help you.

Thanks for investigating this issue thorougly!

Haabster

Hendrik-Jaap in 't Veld
+316 558 324 57 | hendrikjaap@gmail.com | Jasmijn 18 | 2286 KV Rijswijk

**Comment by Flockey** [comment]
Hello Guys,
Mike please let us know if you can fix this problem, i'm trying to find a workaround since 2 weeks, but as jkriester said - this problem occurs only on fresh installs.

I installed WP and WC at least 8 times - automatic per WP and manually, tried every different settings, but i cant get this working. I always get the "(Includes € 0,00 VAT)" .. 

thanking you in anticipation
f

**Comment by mikejolley** [comment]
@Haabster can you email FTP as well

**Comment by Haabster** [comment]
Dear Mike,

Thanks again!

FTP acces via: ftp.projecth.nl, port 21
user: projecth.nl
pas: Temporary2531PassWord

Haabster

Hendrik-Jaap in 't Veld
+316 558 324 57 | hendrikjaap@gmail.com | Jasmijn 18 | 2286 KV Rijswijk

**Comment by mikejolley** [comment]
It is not working because you are missing a database table.

`
WordPress database error: [Specified key was too long; max key length is 1000 bytes]
CREATE TABLE 0_woocommerce_tax_rate_locations ( location_id bigint(20) NOT NULL auto_increment, location_code varchar(255) NOT NULL, tax_rate_id bigint(20) NOT NULL, location_type varchar(40) NOT NULL, PRIMARY KEY (location_id), KEY tax_rate_id (tax_rate_id), KEY location_type (location_type), KEY location_type_code (location_type,location_code) ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
`

Not sure why this isn't installing on your server - check with your host.

**Comment by jkriester** [comment]
Thanks to Mike thank you x3,
I was able to find the fix, as follows:

This database table is missing: "wp_woocommerce_tax_rate_locations"

1 Go to database of webshop that is working correctly
2 Export the database table "wp_woocommerce_tax_rate_locations": select it on left side; on right side tab select export; all setting can be left default
3 Go to databse of webshop that is NOT calculating VAT
4 Import the database table "wp_woocommerce_tax_rate_locations"; on right side tab select import
5 now its fixed

(I cant share this db table with you all here, file type is not supported. Dont not other solution here, or send me message and Ill send it over)

**Comment by mikejolley** [comment]
Any ideas why your prefix was 0_?

**Comment by Haabster** [comment]
@mikejolley: this is how it was setup by our host. They have a one-click wordpress setup. I was not able to edit the settings at all. 

After reading and fiddling around; I found the following: I was not allowed to create the table using PHPMyAdmin. Same error. After changing the character encoding to latin1 and the collation to latin1-swedish_ci it is working so far so good. I am not shure what the consequenses are for the woocommerce. SInce this is only a test shop (not the real deal) I will accept this as a solution so far. I am aware that this solution might breed new problems, but we'll see that later on...

**Comment by Marcelcreech** [comment]
hi guys, i fixed this as well. in my case this was an dutch implementation on one.com, they have this provider roll out of wordpress. The fix: create the missing table, just 5 minutes of work. i could provide you with the screendump if you like.

**Comment by Suzannaa** [comment]
Hi everyone,

I see this is a old topic, but I have exactly the same problem as in the opening post. I tried every option, but still there is 0.00 VAT in the checkout page, when I put a product in the cart. All the pictures in the opening post are showing the exact things as in my options. Only I selected "taxes included" at "Show prices at the store" and "Show prices and order during checkout". And "Yes" on "Prices imported taxes". 

I just checked myphpadmin and there is already a table "wp_woocommerce_tax_rate_locations". So I think they fixed this in the meantime. However... I still got the same problem.

Can you help me?

Kind regards,
Suzanne

**Comment by Marcelcreech** [comment]
Yes, some hosting providers like one.com don't roll out a fully wordpress installation by default. You have to find the missing table and put in in by hand. Inhave to digg back to find out the exact solution.

Marcel

**Comment by Suzannaa** [comment]
Hi Marcel,

Thanks for your quick respons. My hosting provider is MijnDomein. How could I find the missing table? 
I checked a lot of topics by now, but unfortunately I still don't find the solution. Thanks for helping!

Kind regards,
Suzanne

**Comment by Marcelcreech** [comment]
Do you have other wordpress implementations on other platforms? You could try to compair the commerce tables.

Marcel

**Comment by Suzannaa** [comment]
Hi Marcel,

Unfortunately I only have one shop/database.

Kind regards,
Suzanne

**Comment by Marcelcreech** [comment]
Does this help? 
> 
> 
> http://www.zonkey.co.uk/2015/07/woocommerce-tax-showing-checkout/
> 
> https://github.com/woothemes/woocommerce/issues/8147
> 
> https://wordpress.org/support/topic/woocommerce-taxes-not-working-correctly

Marcel

**Comment by Suzannaa** [comment]
Thanks!

I'm just so surprised! I'm not sure anymore what I did, but suddenly it finally works! 
Now I'm never going to touch the options there again, haha. 

But I have a new problem now. But this is offtopic. 
Somehow the shop isn't showing on www.mywebshop.com anymore. Only if I go to www.mywebshop.com/shop

Do you know where I can solve this problem? I don't remember I changed somthing in those options.

Kind regards,
Suzanne

**Comment by Suzannaa** [comment]
Fixed it both! Thanks for the help.
