### ISSUE TITLE
 "Add All" Option / Button when editing or creating a product is not showing.

### ISSUE THREAD

**Issue by Carnfield** [woothemes/woocommerce#8981]
Version 2.4.6
On a Variable Product:
Got loads of attributes listed, the "Add All" Option / Button within editing a product is not Showing. On all websites / videos and "How to" guides it shows.

If you manually add the Options (Named same as the ones within Product &gt; Attributes section) and then go to Add Variation;-

Create Variation from All Attributes: You get the message "No variations added".

Googled, Removed all but WooCommerce Plugin, used nothing but Default WP Theme, tried everything and the bulk "Add All" button to Attributes isn't showing and Variations don't appear to be working either.

**Comment by WPprodigy** [comment]
Hi Carnfield,

Make sure that you have this option checked: http://cld.wthms.co/1byDB/qBWC08bM

The issue with the add variations options showing w/o having variation attributes was solved in https://github.com/woothemes/woocommerce/issues/8954.

**Comment by Carnfield** [comment]
Yeah, didn't think to try that.

Sorry for the sarcasm.

Makes ZERO difference. Just doesn't show at all.

**Comment by mikejolley** [comment]
Add all? There is a select all button, not add all. Here is a screencast of the process. The variations UI changed in 2.4 so its understandable if resources have not been updated quite yet - seems to work fine though.

![sep 01 2015 12 33](https://cloud.githubusercontent.com/assets/90977/9603062/cb9277fc-50a5-11e5-885f-17b1d7b2ac3e.gif)

**Comment by Carnfield** [comment]
Yeah that still doesn't show, being pedantic about the phrasing is an
amazing way to piss your customers off.

Latest version of your plugin, on a clean install, going through 2012/13
etc themes with no other plugins and the buttons don't work, gouranga.

I've already told the person who closed the ticket I'll be going elsewhere.

Do you honestly think a web develop is so retarded he'd miss the button
because the text was slightly different, when I'm telling you no button
shows?

Thanks, Best of luck doing business in future.

PS.  It also seems like there's a few people having this issue and hundreds
of people who are missing the buttons after updating the plugin.

On 1 September 2015 at 12:34, Mike Jolley <notifications@github.com> wrote:

> Add all? There is a select all button, not add all. Here is a screencast
> of the process. The variations UI changed in 2.4 so its understandable if
> resources have not been updated quite yet - seems to work fine though.
>
> [image: sep 01 2015 12 33]
> <https://cloud.githubusercontent.com/assets/90977/9603062/cb9277fc-50a5-11e5-885f-17b1d7b2ac3e.gif>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/woothemes/woocommerce/issues/8981#issuecomment-136681182>
> .
>



-- 
Kind Regards;

Adam King
Head Designer & Developer
*Carnfield Web Design Ltd.*

*T: 0115 888 2772*
W: www.carnfieldwebdesign.co.uk

Marketing | Graphic Design & Branding | Web Design | eCommerce Solutions |
Search Engine Optimisation | Web Hosting

This e-mail (including attachments) is intended only for the person(s) to
whom it is addressed & may be confidential. If you have received this
e-mail in error please contact the sender and delete the message from your
system.

Carnfield Web Design Ltd - Registered Number: 08061045 - Registered Office:
Peartree House, 68 The Common, South Normanton, DE55 2EN.

Strictly meetings by appointment only.

**Comment by mikejolley** [comment]
@Carnfield being a sarcastic ass is also an amazing way of getting no assistance. Without replicating a problem it is virtually impossible to fix, especially with such a vague (and clearly mis-explained) first ticket. 

https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

Maybe you can be a little more clear about what in my above video is not displaying, because that is also a clean install. If I can replicate the issue, I'll reopen it.

> PS.  It also seems like there's a few people having this issue and hundreds
of people who are missing the buttons after updating the plugin.

This is the first report of an 'add all' button being missing on attributes. The support queries are regarding the frontend.
