### ISSUE TITLE
Upgraded to WP 4.4, product images broken in admin panel

### ISSUE THREAD

**Issue by samadsajanlal** [woothemes/woocommerce#9795]
Product images are broken in the admin panel after WP upgrade to 4.4. WP was upgraded using admin panel upgrade functionality.
WooCommerce 2.4.11
I have run "regenerate thumbnails" and the issue is not resolved. The customer facing side images work fine, only admin panel on the "products" page are broken as well as when I go to edit a product.

After careful inspection it is due to mixed SSL and non-SSL connection in the admin panel. Images are not using SSL by default (while the shop and admin panel is required to use SSL)

**Comment by KhaoMaNee** [comment]
I'm having broken product images on product page side. After choosing product option, the product image doesn't show up, only shows a broken link to original image. Regenerate Thumbnails did not fix the issue either.

**Comment by mikejolley** [comment]
@KhaoMaNee this is for the issue you describe https://github.com/woothemes/woocommerce/commit/8c520dd1592bbf6b5909502d805cf056a2e85b97

**Comment by mikejolley** [comment]
Broken in https://core.trac.wordpress.org/changeset/31614 I think? @claudiosmweb

**Comment by samadsajanlal** [comment]
I upgraded to the new WooCommerce 2.4.12... and the issue is still present. Both admin pages wp-admin/edit.php?post_type=product and wp-admin/post.php?post=###&action=edit  fail to properly use SSL for images when the admin panel is accessed via SSL

**Comment by mikejolley** [comment]
> I upgraded to the new WooCommerce 2.4.12... and the issue is still present. Both admin pages wp-admin/edit.php?post_type=product and wp-admin/post.php?post=###&action=edit fail to properly use SSL for images when the admin panel is accessed via SSL

Edit a "POST" with a featured image - does it do the same?

**Comment by michaelhpdx** [comment]
FWIW: I'm seeing the same issue after upgrade to 4.4 + 2.4.12; Console is logging messages for all thumbnails akin to:

`edit.php?post_type=product:4143 Mixed Content: The page at 'https://www.dalluva.com/wp-admin/edit.php?post_type=product' was loaded over HTTPS, but requested an insecure image 'http://www.dalluva.com/wp-content/uploads/2012/10/vino-italiano-400x6001.jpg'. This request has been blocked; the content must be served over HTTPS.`

The resulting look on the admin Product page looks like this:

![image](https://cloud.githubusercontent.com/assets/16245159/11725033/52e00682-9f2c-11e5-839f-bc21cec48dea.png)

**Comment by SX-R** [comment]
I've also got an issue after updating where images are not showing in the shop and also in admin, just as the image above posted by michaelhpdx shows.  
I'm running WP 4.4 and WC Version 2.4.12, (and WP Rocket) 

Pete

**Comment by distresscode** [comment]
*******FIXED*******
I got it to work correctly on my site. I'm also using WP-Rocket and have the CDN feature enabled in WP Rocket (MaxCDN).

Go to WP-Rocket --> Settings --> CDN --> Uncheck "Enable Content Delivery Network".
Click on Save. Delete WP Rocket Cache. Go to your CDN provider and purge all cache for your pullzone. Go back to the CDN page and re-activate "Enable Content Delivery Network". Hit save. It should be working now. HTH!

**Comment by michaelhpdx** [comment]
Glad to hear it worked for you.  Simply clearing the cache does not work for me; the Admin pages are not cached (and shouldn’t be). I’m using Wordfence for caching. Disabling it and using no cache or CDN does nothing to fix the problem.

Michael


From:  distresscode <notifications@github.com>
Reply-To:  woothemes/woocommerce 

<reply@reply.github.com>
Date:  Thursday, December 10, 2015 at 12:00 PM
To:  woothemes/woocommerce <woocommerce@noreply.github.com>
Cc:  Michael Horne <michael@dalluva.com>
Subject:  Re: [woocommerce] Upgraded to WP 4.4, product images broken in admin panel (#9795)


****FIXED****
I got it to work correctly on my site. I'm also using WP-Rocket and have the CDN feature enabled in WP Rocket (MaxCDN).

Go to WP-Rocket --> Settings --> CDN --> Uncheck "Enable Content Delivery Network".
Click on Save. Delete WP Rocket Cache. Go to your CDN provider and purge all cache for your pullzone. Go back to the CDN page and re-activate "Enable Content Delivery Network". Hit save. It should be working now. HTH!

**Comment by samadsajanlal** [comment]
@mikejolley I did what you recommended on a normal blog post. The featured image in the admin panel does not show. It does work on the front end.

Since it appears to be a wordpress core bug, are you able to escalate it or do you need me to go report it there?

For the record: my copy of wordpress does not use CDN or caching of any sort (except maybe on nginx... no plugins on WP)

**Comment by mikejolley** [comment]
For those who have not fixed the issue yet, please post your system status reports and inform us which host you're with.

Also test the same thing with posts as it looks like it may be WP core rather than just WooCommerce.

> @mikejolley I did what you recommended on a normal blog post. The featured image in the admin panel does not show. It does work on the front end.

See this core ticket https://core.trac.wordpress.org/ticket/34945

**Comment by distresscode** [comment]
I just noticed the thread title. Sorry about that. My admin panel is working fine but Mike Jolley asked me to post in this thread to make it easier for him to track the same problem. To clarify, my solution fixes the problem where the main image does not update to reflect the variation image in the product pages. 

@samadsajanlal  You should be able to purge the cache for Nginx in your host's CP. If not, contact your host support and they can do that for you.

**Comment by samadsajanlal** [comment]
@mikejolly to be honest the "workaround" suggested in the ticket is not a very good one. I don't want HTTPS across every page. I just want it on transaction pages and the admin panel. The workaround suggested there will make every page HTTPS regardless of confidentiality of the page

Re: system report (removed URL). I have my own VPS.

```

### WordPress Environment ###

Home URL: http://www.xxxxx.com
Site URL: http://www.xxxxx.com
WC Version: 2.4.12
Log Directory Writable: ✔  /var/www/clients/client1/web18/web/wp-content/uploads/wc-logs/
WP Version: 4.4
WP Multisite: –
WP Memory Limit: 40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: nginx/1.8.0
PHP Version: 5.3.10-1ubuntu3.21 - We recommend a minimum PHP version of 5.4. See: How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.46
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.4.12
: 
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (11) ###

All Meta Tags: by Arthur "Berserkr" Gareginyan – 1.2
Bitpay Woocommerce: by Japhet Stevens
Rich Morgan – 1.2

FooBox Free Image Lightbox: by FooPlugins – 1.0.8
Google XML Sitemaps: by Arne Brachhold – 4.0.8
Hello Dolly: by Matt Mullenweg – 1.6
iFeature Slider Free: by CyberChimps inc. – 1.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.5
Stripe WooCommerce Addon: by Syed Nazrul Hassan – 1.0.5
WooCommerce Google Analytics Integration: by WooThemes – 1.4.0
WooCommerce: by WooThemes – 2.4.12
WP-Mail-SMTP: by Callum Macdonald – 0.9.5

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: –
API Version: 3.0.0

### WC Pages ###

Shop Base: #32 - /
Cart: #33 - /cart/
Checkout: #34 - /checkout/
My Account: #35 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Responsive
Version: 1.9.7.7
Author URL: http://cyberchimps.com
Child Theme: ✕ – If you're modifying WooCommerce or a parent theme you didn't build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

**Comment by distresscode** [comment]
@samadsajanlal  Food for thought.. Google prefers site-wide HTTPS now.

**Comment by samadsajanlal** [comment]
@distresscode thanks... might have to use the workaround anyway then. now to figure out how to redirect all http traffic to https for this specific domain... but that's not an issue for this ticket! :)

**Comment by distresscode** [comment]
I forgot the name but I'll recommend the plugin I'm using to redirect all
traffic to https once I'm back in the office in about half an hour. I used
to redirect traffic using the htaccess but that caused all kinda problems.
The plugin I'm using is amazing.

**Comment by mikejolley** [comment]
@samadsajanlal running everything over https is a good thing, and it can be good for SEO too more recently.

> I forgot the name but I'll recommend the plugin I'm using to redirect all
traffic to https

If the site and home URL are https, WordPress will handle the redirection.

**Comment by michaelhpdx** [comment]
Fascinating. When I use a fresh Safari browser (cache cleaned), the thumbnail problem on the Products page is gone. I cleared the cache on my usual Chrome browser, but the problem is still there.

Here's what things (properly) look like with the Safari browser:
<img width="459" alt="screen shot 2015-12-10 at 1 03 20 pm" src="https://cloud.githubusercontent.com/assets/16245159/11728437/ab92f124-9f3e-11e5-8433-892e4b7567cd.png">

Michael

**Comment by distresscode** [comment]
@samadsajanlal  It's WP Force SSL by Kostas Vrouvas https://wordpress.org/plugins/wp-force-ssl/

**Comment by distresscode** [comment]
@michaelhpdx FYI, chrome always gives me problems when it comes to clearing its cache which is why I use Firefox to debug or when working with code.

**Comment by mikejolly** [comment]
hey y'all - i've been incorrectly roped into this convo, just fyi

**Comment by SX-R** [comment]
The work around didn't work for me, I don't use a cdn yet as I'm setting up the site, but I flushed cache, deactivated WP Rocket and opened my site in a new safari browser and it's still the same,
I use my own dedicated server. 

I will add that when I first see the images weren't showing after I updated WC I reinstalled the previous version of WC and the images still wouldn't show, so it may be something to do with the update to WP 4.4 that I run prior to upgrading WC. It's not just admin images for me as my product  images and variations don't show on the product page. 

WordPress Environment
Home URL:	[?]	http://www.XXXX.co.uk
Site URL:	[?]	http://www.XXXX.co.uk
WC Version:	[?]	2.4.12
Log Directory Writable:	[?]	✔ /home/XXXX/public_html/wp-content/uploads/wc-logs/
WP Version:	[?]	4.4
WP Multisite:	[?]	–
WP Memory Limit:	[?]	100 MB
WP Debug Mode:	[?]	–
Language:	[?]	en_US
Server Environment
Server Info:	[?]	Apache
PHP Version:	[?]	5.5.30
PHP Post Max Size:	[?]	128 MB
PHP Time Limit:	[?]	300
PHP Max Input Vars:	[?]	1000
SUHOSIN Installed:	[?]	–
MySQL Version:	[?]	5.5.5
Max Upload Size:	[?]	128 MB
Default Timezone is UTC:	[?]	✔
fsockopen/cURL:	[?]	 ✔
SoapClient:	[?]	 ✔
DOMDocument:	[?]	 ✔
GZip:	[?]	 ✔
Remote Post:	[?]	✕ wp_remote_post() failed. PayPal IPN won't work with your server. Contact your hosting provider. Error: Connection timed out after 60000 milliseconds
Remote Get:	[?]	 ✔
Database
WC Database Version:	[?]	2.4.12
woocommerce_api_keys	 	✔
woocommerce_attribute_taxonomies	 	✔
woocommerce_termmeta	 	✔
woocommerce_downloadable_product_permissions	 	✔
woocommerce_order_items	 	✔
woocommerce_order_itemmeta	 	✔
woocommerce_tax_rates	 	✔
woocommerce_tax_rate_locations	 	✔
Active Plugins (12)
Coming soon and Maintenance mode WpDevArt	 	by maintenance mode GG, wpdevart, big ben keeper – 2.2.4
GTmetrix for WordPress	 	by GTmetrix – 0.4.1
WooMedia WooCommerce Royal Mail & Parcelforce	 	by WooMedia Inc. – 1.0.2
WooCommerce Custom Fields	 	by RightPress – 1.1.1
WooCommerce Amazon Payments Advanced Gateway	 	by WooThemes – 1.4.6
WooCommerce Grid / List toggle	 	by jameskoster – 1.0.0
WooCommerce	 	by WooThemes – 2.4.12
WooThemes Helper	 	by WooThemes – 1.5.9
Yoast SEO	 	by Team Yoast – 3.0.6
WordPress Social Login	 	by Miled – 2.3.0
WP Rocket	 	by WP Rocket – 2.6.13
WP Smush	 	by WPMU DEV – 2.1.2
Settings
Force SSL:	[?]	–
Currency	[?]	GBP (£)
Currency Position	[?]	left
Thousand Separator	[?]	,
Decimal Separator	[?]	.
Number of Decimals	[?]	2
API
API Enabled:	[?]	✔
API Version:	[?]	3.0.0
WC Pages
Shop Base:	[?]	#4 - /shop/
Cart:	[?]	#5 - /cart/
Checkout:	[?]	#6 - /checkout/
My Account:	[?]	#7 - /my-account/
Taxonomies [?]
Product Types:	 	external (external), grouped (grouped), simple (simple), variable (variable)
Theme
Name:	[?]	SKT Kraft Pro
Version:	[?]	pro1.0
Author URL:	[?]	http://www.sktthemes.net
Child Theme:	[?]	✕ – If you're modifying WooCommerce or a parent theme you didn't build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support:	[?]	✔
Templates [?]
Overrides:	 	–

**Comment by SX-R** [comment]
Fixed it, Only just seen your link to --> https://core.trac.wordpress.org/ticket/34945
My SiteURL and Home URL were set as http://, once I changed both to https:// this issue is resolved. 
:)

**Comment by chaduk** [comment]
I have the same problem as SX-R - I'm using Woocommerce cloud zoom, the default image doesn't change over when the thumbnails are clicked on. So you basically get the zoom of each thumbnail but the same default image that never changes. Interestingly enough it works properly on safari but not on Chrome and Firefox as SX-R describes. I am not using SSL on my siteurl or homeurl though. Any recommendations?

**Comment by purplebabyhippo** [comment]
My issue was that that WordPress url was http under general settings, although the site url was https. Updating this to https fixed the issue.

**Comment by somethumb** [comment]
However, this update to https for the WordPress URL (important!) and the Site URL (optional) causes the File Downloads to throw a 404 page error. So , even though my Admin is fixed now, and the images are showing up properly in the WooCommerce Products, when purchasing a download, the file is not found. How can this be solved?

**Comment by bluehiveinteractive** [comment]
I can confirm that as soon as I set my site URL and WordPress URL to https:// the thumbnails within the admin for WooCommerce are now showing. I am using WordPress HTTPS(SSL) https://wordpress.org/plugins/wordpress-https/ to force SSL on the site.

**Comment by jfoutch** [comment]
Changing to https under general settings worked for me as well.

**Comment by aldelval** [comment]
So does anybody have a solution compatible with having https only on admin and checkout pages? I'd rather not turn the whole site https.

**Comment by greenbeemedia** [comment]
@mikejolley 

Your commit:https://github.com/woothemes/woocommerce/commit/cc68cd48c5a9651022c33c2d8531c0d2f97a85a6

Causes the product thumbnails in the backend to load the full size, at least on my sites..  This introduces a server load issue when you are showing a lot of products on the admin backend. For whatever reason on my sites, post-thumbnail yields the full size image, even though my configuration sets the thumbnail size to smaller. Is there some setting I can configure to force it to gen a thumbnail for post type images that are stored as 'post-thumbnail'?

I suggest using 'shop_thumbnail' instead of 'post-thumbnail', at least we know that gets generated for WooCommerce.
